UPDATE ${PREFIX}_statistic SET `name`='cooked fish' WHERE `statistic`='cookedfish_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cooked fish' WHERE `statistic`='cookedfish_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cooked fish' WHERE `statistic`='cookedfish_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cooked fish' WHERE `statistic`='cookedfish_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='piston base' WHERE `statistic`='pistonbase' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='birch wood stairs' WHERE `statistic`='birchwoodstairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leather chestplate' WHERE `statistic`='leatherchestplate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='raw fish' WHERE `statistic`='rawfish_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='raw fish' WHERE `statistic`='rawfish_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='raw fish' WHERE `statistic`='rawfish_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='raw fish' WHERE `statistic`='rawfish_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='piston moving piece' WHERE `statistic`='pistonmovingpiece' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cooked chicken' WHERE `statistic`='cookedchicken' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_13' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_14' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_15' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='spider' WHERE `statistic`='spider' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone hoe' WHERE `statistic`='stonehoe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_10' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_11' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone torch off' WHERE `statistic`='redstonetorchoff' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_12' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ender portal frame' WHERE `statistic`='enderportalframe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='torch' WHERE `statistic`='torch' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jungle log' WHERE `statistic`='log_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='birch log' WHERE `statistic`='log_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redwood log' WHERE `statistic`='log_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='golden apple' WHERE `statistic`='goldenapple' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='generic log' WHERE `statistic`='log_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='trap door' WHERE `statistic`='trapdoor' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond axe' WHERE `statistic`='diamondaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='slime ball' WHERE `statistic`='slimeball' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='quartz ore' WHERE `statistic`='quartzore' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cauldron' WHERE `statistic`='cauldron' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='magic' WHERE `statistic`='magic' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='baked potato' WHERE `statistic`='bakedpotato' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone spade' WHERE `statistic`='stonespade' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='clay brick' WHERE `statistic`='claybrick' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hay block' WHERE `statistic`='hayblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='item frame' WHERE `statistic`='itemframe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='quartz' WHERE `statistic`='quartz' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='air' WHERE `statistic`='air' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_13' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_12' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_15' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ender signal' WHERE `statistic`='endersignal' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_14' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='magic regen' WHERE `statistic`='magicregen' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron hoe' WHERE `statistic`='ironhoe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='carrot' WHERE `statistic`='carrot' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold record' WHERE `statistic`='goldrecord' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron door' WHERE `statistic`='irondoor' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='melon seeds' WHERE `statistic`='melonseeds' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='chainmail helmet' WHERE `statistic`='chainmailhelmet' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ender portal' WHERE `statistic`='enderportal' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron chestplate' WHERE `statistic`='ironchestplate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='command minecart' WHERE `statistic`='commandminecart' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leash hitch' WHERE `statistic`='leashhitch' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='glowstone' WHERE `statistic`='glowstone' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone torch on' WHERE `statistic`='redstonetorchon' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron sword' WHERE `statistic`='ironsword' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='map' WHERE `statistic`='map' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='generic wood step' WHERE `statistic`='woodstep_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sheep' WHERE `statistic`='sheep' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redwood wood step' WHERE `statistic`='woodstep_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='acacia stairs' WHERE `statistic`='acaciastairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='birch wood step' WHERE `statistic`='woodstep_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jungle wood step' WHERE `statistic`='woodstep_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='painting' WHERE `statistic`='painting' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood double step' WHERE `statistic`='doublestep_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cobblestone double step' WHERE `statistic`='doublestep_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sand' WHERE `statistic`='sand' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold sword' WHERE `statistic`='goldsword' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brick double step' WHERE `statistic`='doublestep_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='smooth_brick double step' WHERE `statistic`='doublestep_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='nether_brick double step' WHERE `statistic`='doublestep_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='quartz_block double step' WHERE `statistic`='doublestep_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bookshelf' WHERE `statistic`='bookshelf' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='web' WHERE `statistic`='web' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron block' WHERE `statistic`='ironblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='boat' WHERE `statistic`='boat' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fire' WHERE `statistic`='fire' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='snow block' WHERE `statistic`='snowblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron fence' WHERE `statistic`='ironfence' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cocoa' WHERE `statistic`='cocoa' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='crops' WHERE `statistic`='crops' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sandstone double step' WHERE `statistic`='doublestep_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone double step' WHERE `statistic`='doublestep_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='smooth brick' WHERE `statistic`='smoothbrick' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='nether star' WHERE `statistic`='netherstar' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='player' WHERE `statistic`='player' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='rails' WHERE `statistic`='rails' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone' WHERE `statistic`='stone' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='blaze powder' WHERE `statistic`='blazepowder' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='falling block' WHERE `statistic`='fallingblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond ore' WHERE `statistic`='diamondore' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='chainmail leggings' WHERE `statistic`='chainmailleggings' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='witch' WHERE `statistic`='witch' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron helmet' WHERE `statistic`='ironhelmet' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brick stairs' WHERE `statistic`='brickstairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='powered rail' WHERE `statistic`='poweredrail' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone lamp off' WHERE `statistic`='redstonelampoff' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='pumpkin' WHERE `statistic`='pumpkin' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='watch' WHERE `statistic`='watch' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ender crystal' WHERE `statistic`='endercrystal' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sign' WHERE `statistic`='sign' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='weakness' WHERE `statistic`='weakness' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leash' WHERE `statistic`='leash' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='saddle' WHERE `statistic`='saddle' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose_8' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold ingot' WHERE `statistic`='goldingot' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='trapped chest' WHERE `statistic`='trappedchest' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fire tick' WHERE `statistic`='firetick' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diode' WHERE `statistic`='diode' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='log flower pot' WHERE `statistic`='flowerpot_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='log flower pot' WHERE `statistic`='flowerpot_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='packed ice' WHERE `statistic`='packedice' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brown_mushroom flower pot' WHERE `statistic`='flowerpot_8' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red_mushroom flower pot' WHERE `statistic`='flowerpot_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cactus flower pot' WHERE `statistic`='flowerpot_9' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='magma cube' WHERE `statistic`='magmacube' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='horse' WHERE `statistic`='horse' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold pickaxe' WHERE `statistic`='goldpickaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hopper minecart' WHERE `statistic`='hopperminecart' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='blaze' WHERE `statistic`='blaze' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dark oak stairs' WHERE `statistic`='darkoakstairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron plate' WHERE `statistic`='ironplate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='piston extension' WHERE `statistic`='pistonextension' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond sword' WHERE `statistic`='diamondsword' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='exp bottle' WHERE `statistic`='expbottle' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='primed tnt' WHERE `statistic`='primedtnt' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='water lily' WHERE `statistic`='waterlily' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sponge' WHERE `statistic`='sponge' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='carrot item' WHERE `statistic`='carrotitem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='explosive minecart' WHERE `statistic`='explosiveminecart' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ice' WHERE `statistic`='ice' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='coal' WHERE `statistic`='coal' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cave spider' WHERE `statistic`='cavespider' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='netherrack' WHERE `statistic`='netherrack' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='flower pot' WHERE `statistic`='flowerpot_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red_rose flower pot' WHERE `statistic`='flowerpot_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='quartz block' WHERE `statistic`='quartzblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='yellow_flower flower pot' WHERE `statistic`='flowerpot_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='log flower pot' WHERE `statistic`='flowerpot_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='log flower pot' WHERE `statistic`='flowerpot_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='speed' WHERE `statistic`='speed' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='daylight detector' WHERE `statistic`='daylightdetector' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='starvation' WHERE `statistic`='starvation' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='tripwire' WHERE `statistic`='tripwire' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dead_bush flower pot' WHERE `statistic`='flowerpot_10' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='long_grass flower pot' WHERE `statistic`='flowerpot_11' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diode block off' WHERE `statistic`='diodeblockoff' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='flower pot' WHERE `statistic`='flowerpot_12' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='burning furnace' WHERE `statistic`='burningfurnace' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='flower pot' WHERE `statistic`='flowerpot_13' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ink sack' WHERE `statistic`='inksack' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone block' WHERE `statistic`='redstoneblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bow' WHERE `statistic`='bow' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='pumpkin pie' WHERE `statistic`='pumpkinpie' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='coal block' WHERE `statistic`='coalblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='minecart' WHERE `statistic`='minecart' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cooked beef' WHERE `statistic`='cookedbeef' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold plate' WHERE `statistic`='goldplate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ender dragon' WHERE `statistic`='enderdragon' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='suffocation' WHERE `statistic`='suffocation' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='quartz stairs' WHERE `statistic`='quartzstairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sandstone stairs' WHERE `statistic`='sandstonestairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='slime' WHERE `statistic`='slime' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='emerald' WHERE `statistic`='emerald' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bread' WHERE `statistic`='bread' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='entity attack' WHERE `statistic`='entityattack' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='workbench' WHERE `statistic`='workbench' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='mossy cobblestone' WHERE `statistic`='mossycobblestone' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='coal coal' WHERE `statistic`='coal_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='charcoal coal' WHERE `statistic`='coal_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='vine' WHERE `statistic`='vine' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='pumpkin stem' WHERE `statistic`='pumpkinstem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='melon' WHERE `statistic`='melon' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='small fireball' WHERE `statistic`='smallfireball' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='note block' WHERE `statistic`='noteblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron axe' WHERE `statistic`='ironaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bat' WHERE `statistic`='bat' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='coal ore' WHERE `statistic`='coalore' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='clay ball' WHERE `statistic`='clayball' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='silverfish' WHERE `statistic`='silverfish' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold nugget' WHERE `statistic`='goldnugget' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fishing rod' WHERE `statistic`='fishingrod' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='block explosion' WHERE `statistic`='blockexplosion' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='flower pot item' WHERE `statistic`='flowerpotitem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='pig zombie' WHERE `statistic`='pigzombie' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='shears' WHERE `statistic`='shears' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='monster eggs' WHERE `statistic`='monstereggs_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='lime ink sack' WHERE `statistic`='inksack_10' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_9' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='monster eggs' WHERE `statistic`='monstereggs_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='yellow ink sack' WHERE `statistic`='inksack_11' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_8' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red rose' WHERE `statistic`='redrose' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='potato item' WHERE `statistic`='potatoitem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='grilled pork' WHERE `statistic`='grilledpork' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='monster eggs' WHERE `statistic`='monstereggs_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='orange ink sack' WHERE `statistic`='inksack_14' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='white ink sack' WHERE `statistic`='inksack_15' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood door' WHERE `statistic`='wooddoor' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='monster eggs' WHERE `statistic`='monstereggs_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='light_blue ink sack' WHERE `statistic`='inksack_12' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='magenta ink sack' WHERE `statistic`='inksack_13' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='chicken' WHERE `statistic`='chicken' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='melting' WHERE `statistic`='melting' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond helmet' WHERE `statistic`='diamondhelmet' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='nether stalk' WHERE `statistic`='netherstalk' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='regen' WHERE `statistic`='regen' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone ore' WHERE `statistic`='redstoneore' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood plate' WHERE `statistic`='woodplate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond spade' WHERE `statistic`='diamondspade' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='smooth stairs' WHERE `statistic`='smoothstairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='water bucket' WHERE `statistic`='waterbucket' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='water' WHERE `statistic`='water' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cake block' WHERE `statistic`='cakeblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leaves 2' WHERE `statistic`='leaves2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='eye of ender' WHERE `statistic`='eyeofender' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='void' WHERE `statistic`='void' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='unknown' WHERE `statistic`='unknown' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='water breathing' WHERE `statistic`='waterbreathing' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='complex part' WHERE `statistic`='complexpart' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 9' WHERE `statistic`='record9' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 3' WHERE `statistic`='record3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='golden carrot' WHERE `statistic`='goldencarrot' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 4' WHERE `statistic`='record4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold barding' WHERE `statistic`='goldbarding' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 7' WHERE `statistic`='record7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 8' WHERE `statistic`='record8' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='written book' WHERE `statistic`='writtenbook' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 5' WHERE `statistic`='record5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 6' WHERE `statistic`='record6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='green ink sack' WHERE `statistic`='inksack_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red ink sack' WHERE `statistic`='inksack_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='activator rail' WHERE `statistic`='activatorrail' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='black ink sack' WHERE `statistic`='inksack_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron ore' WHERE `statistic`='ironore' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leather helmet' WHERE `statistic`='leatherhelmet' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='firework charge' WHERE `statistic`='fireworkcharge' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='carpet' WHERE `statistic`='carpet' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='melon stem' WHERE `statistic`='melonstem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='huge mushroom 2' WHERE `statistic`='hugemushroom2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='huge mushroom 1' WHERE `statistic`='hugemushroom1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='rotten flesh' WHERE `statistic`='rottenflesh' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='splash potion' WHERE `statistic`='splashpotion' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='flint' WHERE `statistic`='flint' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='pink ink sack' WHERE `statistic`='inksack_9' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ender stone' WHERE `statistic`='enderstone' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='silver ink sack' WHERE `statistic`='inksack_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='thorns' WHERE `statistic`='thorns' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gray ink sack' WHERE `statistic`='inksack_8' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='purple ink sack' WHERE `statistic`='inksack_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dirt' WHERE `statistic`='dirt' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cyan ink sack' WHERE `statistic`='inksack_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='lever' WHERE `statistic`='lever' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brown ink sack' WHERE `statistic`='inksack_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='blue ink sack' WHERE `statistic`='inksack_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold ore' WHERE `statistic`='goldore' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='minecart chest' WHERE `statistic`='minecartchest' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bed' WHERE `statistic`='bed' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='minecart furnace' WHERE `statistic`='minecartfurnace' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone comparator' WHERE `statistic`='redstonecomparator' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_9' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='double step' WHERE `statistic`='doublestep' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone pickaxe' WHERE `statistic`='stonepickaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_8' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cooked fish' WHERE `statistic`='cookedfish' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='glowing redstone ore' WHERE `statistic`='glowingredstoneore' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='apple' WHERE `statistic`='apple' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='tripwire hook' WHERE `statistic`='tripwirehook' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='blaze rod' WHERE `statistic`='blazerod' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='pumpkin seeds' WHERE `statistic`='pumpkinseeds' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='instant heal' WHERE `statistic`='instantheal' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stick' WHERE `statistic`='stick' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cobblestone smooth brick' WHERE `statistic`='smoothbrick_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='smooth_brick smooth brick' WHERE `statistic`='smoothbrick_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='firework' WHERE `statistic`='firework' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone smooth brick' WHERE `statistic`='smoothbrick_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='mossy_cobblestone smooth brick' WHERE `statistic`='smoothbrick_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stationary lava' WHERE `statistic`='stationarylava' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='enderman' WHERE `statistic`='enderman' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='chest' WHERE `statistic`='chest' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_10' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass pane' WHERE `statistic`='stainedglasspane_11' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jungle leaves' WHERE `statistic`='leaves_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='birch leaves' WHERE `statistic`='leaves_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redwood leaves' WHERE `statistic`='leaves_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='generic leaves' WHERE `statistic`='leaves_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold axe' WHERE `statistic`='goldaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='speckled melon' WHERE `statistic`='speckledmelon' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond' WHERE `statistic`='diamond' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='potion' WHERE `statistic`='potion' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='lapis block' WHERE `statistic`='lapisblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ghast tear' WHERE `statistic`='ghasttear' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='lava bucket' WHERE `statistic`='lavabucket' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sugar cane block' WHERE `statistic`='sugarcaneblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained glass' WHERE `statistic`='stainedglass' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='chainmail chestplate' WHERE `statistic`='chainmailchestplate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='creeper' WHERE `statistic`='creeper' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='pig' WHERE `statistic`='pig' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wooden door' WHERE `statistic`='woodendoor' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ghast' WHERE `statistic`='ghast' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='lava' WHERE `statistic`='lava' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brewing stand item' WHERE `statistic`='brewingstanditem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone' WHERE `statistic`='redstone' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='milk bucket' WHERE `statistic`='milkbucket' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='glowstone dust' WHERE `statistic`='glowstonedust' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='eating' WHERE `statistic`='eating' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='enchanted book' WHERE `statistic`='enchantedbook' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sign post' WHERE `statistic`='signpost' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='step' WHERE `statistic`='step' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='flower pot' WHERE `statistic`='flowerpot' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone lamp on' WHERE `statistic`='redstonelampon' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sugar' WHERE `statistic`='sugar' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone button' WHERE `statistic`='stonebutton' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood' WHERE `statistic`='wood' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='enchantment table' WHERE `statistic`='enchantmenttable' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='arrow' WHERE `statistic`='arrow' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond pickaxe' WHERE `statistic`='diamondpickaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='villager' WHERE `statistic`='villager' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fermented spider eye' WHERE `statistic`='fermentedspidereye' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond barding' WHERE `statistic`='diamondbarding' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='storage minecart' WHERE `statistic`='storageminecart' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='soul sand' WHERE `statistic`='soulsand' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold chestplate' WHERE `statistic`='goldchestplate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='snow' WHERE `statistic`='snow' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stationary water' WHERE `statistic`='stationarywater' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diode block on' WHERE `statistic`='diodeblockon' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wool' WHERE `statistic`='wool' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='suicide' WHERE `statistic`='suicide' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dragon egg' WHERE `statistic`='dragonegg' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood sword' WHERE `statistic`='woodsword' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond hoe' WHERE `statistic`='diamondhoe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='snowball' WHERE `statistic`='snowball' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ender chest' WHERE `statistic`='enderchest' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leather leggings' WHERE `statistic`='leatherleggings' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='double plant' WHERE `statistic`='doubleplant_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='log' WHERE `statistic`='log' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='double plant' WHERE `statistic`='doubleplant_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='long grass' WHERE `statistic`='longgrass_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cookie' WHERE `statistic`='cookie' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='double plant' WHERE `statistic`='doubleplant_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='double plant' WHERE `statistic`='doubleplant_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='normal long grass' WHERE `statistic`='longgrass_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='double plant' WHERE `statistic`='doubleplant_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fern_like long grass' WHERE `statistic`='longgrass_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dead long grass' WHERE `statistic`='longgrass_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='double plant' WHERE `statistic`='doubleplant_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='detector rail' WHERE `statistic`='detectorrail' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dropper' WHERE `statistic`='dropper' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='empty map' WHERE `statistic`='emptymap' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bucket' WHERE `statistic`='bucket' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bed block' WHERE `statistic`='bedblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='monster egg' WHERE `statistic`='monsteregg' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gravel' WHERE `statistic`='gravel' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='nether fence' WHERE `statistic`='netherfence' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond block' WHERE `statistic`='diamondblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='raw chicken' WHERE `statistic`='rawchicken' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='name tag' WHERE `statistic`='nametag' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='log 2' WHERE `statistic`='log2_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron spade' WHERE `statistic`='ironspade' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='furnace' WHERE `statistic`='furnace' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood axe' WHERE `statistic`='woodaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='seeds' WHERE `statistic`='seeds' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='projectile' WHERE `statistic`='projectile' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron golem' WHERE `statistic`='irongolem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron door block' WHERE `statistic`='irondoorblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold hoe' WHERE `statistic`='goldhoe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone axe' WHERE `statistic`='stoneaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='log 2' WHERE `statistic`='log2_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond chestplate' WHERE `statistic`='diamondchestplate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red mushroom' WHERE `statistic`='redmushroom' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone wire' WHERE `statistic`='redstonewire' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='string' WHERE `statistic`='string' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone plate' WHERE `statistic`='stoneplate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wall sign' WHERE `statistic`='wallsign' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cobble wall' WHERE `statistic`='cobblewall' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sulphur' WHERE `statistic`='sulphur' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cow' WHERE `statistic`='cow' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='experience orb' WHERE `statistic`='experienceorb' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold leggings' WHERE `statistic`='goldleggings' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='yellow flower' WHERE `statistic`='yellowflower' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wither' WHERE `statistic`='wither' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='obsidian' WHERE `statistic`='obsidian' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='poisonous potato' WHERE `statistic`='poisonouspotato' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_11' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='thrown exp bottle' WHERE `statistic`='thrownexpbottle' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_10' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='slowness' WHERE `statistic`='slowness' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='locked chest' WHERE `statistic`='lockedchest' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='invisibility' WHERE `statistic`='invisibility' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_15' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cauldron item' WHERE `statistic`='cauldronitem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_14' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leather boots' WHERE `statistic`='leatherboots' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leather' WHERE `statistic`='leather' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_13' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_12' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron ingot' WHERE `statistic`='ironingot' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='poison' WHERE `statistic`='poison' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='thin glass' WHERE `statistic`='thinglass' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron leggings' WHERE `statistic`='ironleggings' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='lightning' WHERE `statistic`='lightning' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='chainmail boots' WHERE `statistic`='chainmailboots' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond leggings' WHERE `statistic`='diamondleggings' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cobblestone stairs' WHERE `statistic`='cobblestonestairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='tnt' WHERE `statistic`='tnt' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood double step' WHERE `statistic`='wooddoublestep' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone comparator off' WHERE `statistic`='redstonecomparatoroff' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='monster eggs' WHERE `statistic`='monstereggs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wither spawn' WHERE `statistic`='witherspawn' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brick' WHERE `statistic`='brick' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sandstone' WHERE `statistic`='sandstone' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='skull item' WHERE `statistic`='skullitem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='nether brick stairs' WHERE `statistic`='netherbrickstairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='compass' WHERE `statistic`='compass' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jukebox' WHERE `statistic`='jukebox' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='instant damage' WHERE `statistic`='instantdamage' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='emerald block' WHERE `statistic`='emeraldblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='nether brick' WHERE `statistic`='netherbrick' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='minecart tnt' WHERE `statistic`='minecarttnt' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ladder' WHERE `statistic`='ladder' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bowl' WHERE `statistic`='bowl' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wither skull' WHERE `statistic`='witherskull' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='strength' WHERE `statistic`='strength' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dirt' WHERE `statistic`='dirt_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='diamond boots' WHERE `statistic`='diamondboots' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dirt' WHERE `statistic`='dirt_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fire resistance' WHERE `statistic`='fireresistance' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dirt' WHERE `statistic`='dirt_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dirt' WHERE `statistic`='dirt_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='purple wool' WHERE `statistic`='wool_10' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='blue wool' WHERE `statistic`='wool_11' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='quartz block' WHERE `statistic`='quartzblock_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brown wool' WHERE `statistic`='wool_12' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='quartz block' WHERE `statistic`='quartzblock_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='green wool' WHERE `statistic`='wool_13' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='quartz block' WHERE `statistic`='quartzblock_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='red wool' WHERE `statistic`='wool_14' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wolf' WHERE `statistic`='wolf' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='black wool' WHERE `statistic`='wool_15' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='spruce wood stairs' WHERE `statistic`='sprucewoodstairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ender pearl' WHERE `statistic`='enderpearl' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='potato' WHERE `statistic`='potato' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='giant' WHERE `statistic`='giant' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='satiated' WHERE `statistic`='satiated' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 11' WHERE `statistic`='record11' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_8' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 10' WHERE `statistic`='record10' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_9' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='record 12' WHERE `statistic`='record12' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='raw fish' WHERE `statistic`='rawfish' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leaves' WHERE `statistic`='leaves' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='feather' WHERE `statistic`='feather' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hopper' WHERE `statistic`='hopper' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='spider eye' WHERE `statistic`='spidereye' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='mushroom soup' WHERE `statistic`='mushroomsoup' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='weather' WHERE `statistic`='weather' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='entity explosion' WHERE `statistic`='entityexplosion' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brown mushroom' WHERE `statistic`='brownmushroom' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='grass' WHERE `statistic`='grass' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='powered minecart' WHERE `statistic`='poweredminecart' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redstone comparator on' WHERE `statistic`='redstonecomparatoron' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fence' WHERE `statistic`='fence' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='minecart mob spawner' WHERE `statistic`='minecartmobspawner' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='melon block' WHERE `statistic`='melonblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='carrot stick' WHERE `statistic`='carrotstick' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron barding' WHERE `statistic`='ironbarding' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='mycel' WHERE `statistic`='mycel' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='raw beef' WHERE `statistic`='rawbeef' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron pickaxe' WHERE `statistic`='ironpickaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dead bush' WHERE `statistic`='deadbush' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='contact' WHERE `statistic`='contact' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='zombie' WHERE `statistic`='zombie' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold helmet' WHERE `statistic`='goldhelmet' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='command' WHERE `statistic`='command' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dispenser' WHERE `statistic`='dispenser' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood step' WHERE `statistic`='woodstep' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='drowning' WHERE `statistic`='drowning' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='piston sticky base' WHERE `statistic`='pistonstickybase' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bedrock' WHERE `statistic`='bedrock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jack o lantern' WHERE `statistic`='jackolantern' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jungle sapling' WHERE `statistic`='sapling_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='anvil' WHERE `statistic`='anvil' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='generic sapling' WHERE `statistic`='sapling_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jungle sapling' WHERE `statistic`='sapling_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='birch sapling' WHERE `statistic`='sapling_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='quartz_block step' WHERE `statistic`='step_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redwood sapling' WHERE `statistic`='sapling_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='generic sapling' WHERE `statistic`='sapling_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='smooth_brick step' WHERE `statistic`='step_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='nether_brick step' WHERE `statistic`='step_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='birch sapling' WHERE `statistic`='sapling_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cobblestone step' WHERE `statistic`='step_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redwood sapling' WHERE `statistic`='sapling_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brick step' WHERE `statistic`='step_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fall' WHERE `statistic`='fall' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='beacon' WHERE `statistic`='beacon' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cactus' WHERE `statistic`='cactus' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leaves 2' WHERE `statistic`='leaves2_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redwood wood' WHERE `statistic`='wood_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='generic wood' WHERE `statistic`='wood_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone step' WHERE `statistic`='step_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sandstone step' WHERE `statistic`='step_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood step' WHERE `statistic`='step_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='nether brick item' WHERE `statistic`='netherbrickitem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='egg' WHERE `statistic`='egg' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='leaves 2' WHERE `statistic`='leaves2_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood hoe' WHERE `statistic`='woodhoe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='skull' WHERE `statistic`='skull' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='minecart command' WHERE `statistic`='minecartcommand' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='nether warts' WHERE `statistic`='netherwarts' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jungle wood stairs' WHERE `statistic`='junglewoodstairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='glass bottle' WHERE `statistic`='glassbottle' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cobblestone' WHERE `statistic`='cobblestone' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='night vision' WHERE `statistic`='nightvision' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='dropped item' WHERE `statistic`='droppeditem' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='custom' WHERE `statistic`='custom' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='glyphed sandstone' WHERE `statistic`='sandstone_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cracked sandstone' WHERE `statistic`='sandstone_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood stairs' WHERE `statistic`='woodstairs' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cake' WHERE `statistic`='cake' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='brewing stand' WHERE `statistic`='brewingstand' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sandstone' WHERE `statistic`='sandstone_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='mushroom cow' WHERE `statistic`='mushroomcow' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='portal' WHERE `statistic`='portal' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='smooth sandstone' WHERE `statistic`='sandstone_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='log 2' WHERE `statistic`='log2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='double plant' WHERE `statistic`='doubleplant' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood pickaxe' WHERE `statistic`='woodpickaxe' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='minecart hopper' WHERE `statistic`='minecarthopper' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood spade' WHERE `statistic`='woodspade' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='pork' WHERE `statistic`='pork' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='birch wood' WHERE `statistic`='wood_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jungle wood' WHERE `statistic`='wood_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='generic wood' WHERE `statistic`='wood_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redwood wood' WHERE `statistic`='wood_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='birch wood' WHERE `statistic`='wood_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jungle wood' WHERE `statistic`='wood_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='soil' WHERE `statistic`='soil' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='clay' WHERE `statistic`='clay' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold block' WHERE `statistic`='goldblock' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='ocelot' WHERE `statistic`='ocelot' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='paper' WHERE `statistic`='paper' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='skeleton' WHERE `statistic`='skeleton' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wood button' WHERE `statistic`='woodbutton' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sugar cane' WHERE `statistic`='sugarcane' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='silver wool' WHERE `statistic`='wool_8' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='cyan wool' WHERE `statistic`='wool_9' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold boots' WHERE `statistic`='goldboots' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='pink wool' WHERE `statistic`='wool_6' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='long grass' WHERE `statistic`='longgrass' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gray wool' WHERE `statistic`='wool_7' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stone sword' WHERE `statistic`='stonesword' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='yellow wool' WHERE `statistic`='wool_4' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='lime wool' WHERE `statistic`='wool_5' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='magenta wool' WHERE `statistic`='wool_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='light_blue wool' WHERE `statistic`='wool_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='bone' WHERE `statistic`='bone' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='white wool' WHERE `statistic`='wool_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='glass' WHERE `statistic`='glass' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='orange wool' WHERE `statistic`='wool_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='gold spade' WHERE `statistic`='goldspade' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fishing hook' WHERE `statistic`='fishinghook' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='wheat' WHERE `statistic`='wheat' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='book and quill' WHERE `statistic`='bookandquill' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fence gate' WHERE `statistic`='fencegate' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='generic wood double step' WHERE `statistic`='wooddoublestep_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='flint and steel' WHERE `statistic`='flintandsteel' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='sapling' WHERE `statistic`='sapling' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='mob spawner' WHERE `statistic`='mobspawner' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='jungle wood double step' WHERE `statistic`='wooddoublestep_3' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='redwood wood double step' WHERE `statistic`='wooddoublestep_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='squid' WHERE `statistic`='squid' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='birch wood double step' WHERE `statistic`='wooddoublestep_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_1' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_2' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='hard clay' WHERE `statistic`='hardclay_0' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='stained clay' WHERE `statistic`='stainedclay' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='lapis ore' WHERE `statistic`='lapisore' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='magma cream' WHERE `statistic`='magmacream' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='emerald ore' WHERE `statistic`='emeraldore' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='book' WHERE `statistic`='book' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='green record' WHERE `statistic`='greenrecord' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='snowman' WHERE `statistic`='snowman' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='iron boots' WHERE `statistic`='ironboots' and `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`='fireball' WHERE `statistic`='fireball' and `name` IS NULL;