INSERT IGNORE INTO ${PREFIX}_domain (domain) VALUES ("default");
INSERT IGNORE INTO ${PREFIX}_world (world,name) VALUES ("__global__","Global");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("activatorrail","activator rail");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("air","air");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("anvil","anvil");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("apple","apple");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("arrow","arrow");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bakedpotato","baked potato");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bat","bat");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("beacon","beacon");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bed","bed");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bedblock","bed block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bedrock","bedrock");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("birchwoodstairs","birch wood stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("blaze","blaze");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("blazepowder","blaze powder");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("blazerod","blaze rod");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("blockexplosion","block explosion");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("boat","boat");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bone","bone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("book","book");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bookandquill","book and quill");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bookshelf","bookshelf");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bow","bow");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bowl","bowl");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bread","bread");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("brewingstand","brewing stand");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("brewingstanditem","brewing stand item");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("brick","brick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("brickstairs","brick stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("brownmushroom","brown mushroom");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("bucket","bucket");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("burningfurnace","burning furnace");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cactus","cactus");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cake","cake");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cakeblock","cake block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("carpet","carpet");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("carrot","carrot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("carrotitem","carrot item");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("carrotstick","carrot stick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cauldron","cauldron");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cauldronitem","cauldron item");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cavespider","cave spider");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("chainmailboots","chainmail boots");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("chainmailchestplate","chainmail chestplate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("chainmailhelmet","chainmail helmet");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("chainmailleggings","chainmail leggings");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("chest","chest");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("chicken","chicken");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("clay","clay");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("clayball","clay ball");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("claybrick","clay brick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("coal","coal");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("coal_0","coal coal");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("coal_1","charcoal coal");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("coalblock","coal block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("coalore","coal ore");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cobblestone","cobblestone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cobblestonestairs","cobblestone stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cobblewall","cobble wall");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cocoa","cocoa");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("command","command");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("compass","compass");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("complexpart","complex part");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("contact","contact");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cookedbeef","cooked beef");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cookedchicken","cooked chicken");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cookedfish","cooked fish");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cookie","cookie");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("cow","cow");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("creeper","creeper");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("crops","crops");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("custom","custom");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("daylightdetector","daylight detector");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("deadbush","dead bush");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("detectorrail","detector rail");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamond","diamond");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondaxe","diamond axe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondbarding","diamond barding");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondblock","diamond block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondboots","diamond boots");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondchestplate","diamond chestplate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondhelmet","diamond helmet");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondhoe","diamond hoe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondleggings","diamond leggings");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondore","diamond ore");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondpickaxe","diamond pickaxe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondspade","diamond spade");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diamondsword","diamond sword");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diode","diode");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diodeblockoff","diode block off");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("diodeblockon","diode block on");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("dirt","dirt");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("dispenser","dispenser");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("doublestep","double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("doublestep_0","stone double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("doublestep_1","sandstone double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("doublestep_2","wood double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("doublestep_3","cobblestone double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("doublestep_4","brick double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("doublestep_5","smooth brick double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("doublestep_6","nether brick double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("doublestep_7","quartz block double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("dragonegg","dragon egg");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("droppeditem","dropped item");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("dropper","dropper");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("drowning","drowning");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("eating","eating");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("egg","egg");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("emerald","emerald");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("emeraldblock","emerald block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("emeraldore","emerald ore");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("emptymap","empty map");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("enchantedbook","enchanted book");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("enchantmenttable","enchantment table");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("enderchest","ender chest");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("endercrystal","ender crystal");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("enderdragon","ender dragon");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("enderman","enderman");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("enderpearl","ender pearl");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("enderportal","ender portal");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("enderportalframe","ender portal frame");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("endersignal","ender signal");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("enderstone","ender stone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("entityattack","entity attack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("entityexplosion","entity explosion");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("expbottle","exp bottle");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("experienceorb","experience orb");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("explosiveminecart","explosive minecart");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("eyeofender","eye of ender");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fall","fall");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fallingblock","falling block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("feather","feather");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fence","fence");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fencegate","fence gate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fermentedspidereye","fermented spider eye");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fire","fire");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fireball","fireball");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fireresistance","fire resistance");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("firetick","fire tick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("firework","firework");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fireworkcharge","firework charge");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fishinghook","fishing hook");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("fishingrod","fishing rod");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flint","flint");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flintandsteel","flint and steel");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot","flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_0"," flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_1","red rose flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_10","dead bush flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_11","long grass flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_12"," flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_13"," flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_14"," flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_15"," flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_2","yellow flower flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_3","log flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_4","log flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_5","log flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_6","log flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_7","red mushroom flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_8","brown mushroom flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpot_9","cactus flower pot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("flowerpotitem","flower pot item");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("furnace","furnace");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ghast","ghast");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ghasttear","ghast tear");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("giant","giant");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("glass","glass");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("glassbottle","glass bottle");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("glowingredstoneore","glowing redstone ore");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("glowstone","glowstone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("glowstonedust","glowstone dust");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldaxe","gold axe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldbarding","gold barding");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldblock","gold block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldboots","gold boots");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldchestplate","gold chestplate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldenapple","golden apple");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldencarrot","golden carrot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldhelmet","gold helmet");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldhoe","gold hoe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldingot","gold ingot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldleggings","gold leggings");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldnugget","gold nugget");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldore","gold ore");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldpickaxe","gold pickaxe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldplate","gold plate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldrecord","gold record");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldspade","gold spade");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("goldsword","gold sword");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("grass","grass");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("gravel","gravel");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("greenrecord","green record");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("grilledpork","grilled pork");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("hardclay","hard clay");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("hayblock","hay block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("hopper","hopper");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("hopperminecart","hopper minecart");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("horse","horse");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("hugemushroom1","huge mushroom 1");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("hugemushroom2","huge mushroom 2");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ice","ice");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack","ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_0","black ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_1","red ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_10","lime ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_11","yellow ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_12","light blue ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_13","magenta ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_14","orange ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_15","white ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_2","green ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_3","brown ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_4","blue ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_5","purple ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_6","cyan ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_7","silver ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_8","gray ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("inksack_9","pink ink sack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("instantdamage","instant damage");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("instantheal","instant heal");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("invisibility","invisibility");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironaxe","iron axe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironbarding","iron barding");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironblock","iron block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironboots","iron boots");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironchestplate","iron chestplate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("irondoor","iron door");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("irondoorblock","iron door block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironfence","iron fence");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("irongolem","iron golem");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironhelmet","iron helmet");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironhoe","iron hoe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironingot","iron ingot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironleggings","iron leggings");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironore","iron ore");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironpickaxe","iron pickaxe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironplate","iron plate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironspade","iron spade");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ironsword","iron sword");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("itemframe","item frame");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("jackolantern","jack o lantern");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("jukebox","jukebox");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("junglewoodstairs","jungle wood stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ladder","ladder");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("lapisblock","lapis block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("lapisore","lapis ore");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("lava","lava");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("lavabucket","lava bucket");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leash","leash");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leashhitch","leash hitch");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leather","leather");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leatherboots","leather boots");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leatherchestplate","leather chestplate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leatherhelmet","leather helmet");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leatherleggings","leather leggings");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leaves","leaves");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leaves_0","oak leaves");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leaves_1","redwood leaves");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leaves_2","birch leaves");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("leaves_3","jungle leaves");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("lever","lever");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("lightning","lightning");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("lockedchest","locked chest");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("log","log");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("log_0","oak log");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("log_1","redwood log");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("log_2","birch log");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("log_3","jungle log");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("longgrass","long grass");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("longgrass_0","dead long grass");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("longgrass_1","normal long grass");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("longgrass_2","fern like long grass");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("longgrass_3"," long grass");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("magic","magic");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("magicregen","magic regen");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("magmacream","magma cream");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("magmacube","magma cube");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("map","map");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("melon","melon");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("melonblock","melon block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("melonseeds","melon seeds");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("melonstem","melon stem");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("melting","melting");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("milkbucket","milk bucket");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("minecart","minecart");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("minecartchest","minecart chest");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("minecartfurnace","minecart furnace");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("minecarthopper","minecart hopper");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("minecartmobspawner","minecart mob spawner");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("minecarttnt","minecart tnt");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("mobspawner","mob spawner");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("monsteregg","monster egg");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("monstereggs","monster eggs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("monstereggs_0"," monster eggs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("monstereggs_1"," monster eggs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("monstereggs_2"," monster eggs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("monstereggs_3"," monster eggs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("mossycobblestone","mossy cobblestone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("mushroomcow","mushroom cow");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("mushroomsoup","mushroom soup");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("mycel","mycel");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("nametag","name tag");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("netherbrick","nether brick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("netherbrickitem","nether brick item");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("netherbrickstairs","nether brick stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("netherfence","nether fence");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("netherrack","netherrack");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("netherstalk","nether stalk");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("netherstar","nether star");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("netherwarts","nether warts");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("nightvision","night vision");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("noteblock","note block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("obsidian","obsidian");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("ocelot","ocelot");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("painting","painting");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("paper","paper");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pig","pig");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pigzombie","pig zombie");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pistonbase","piston base");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pistonextension","piston extension");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pistonmovingpiece","piston moving piece");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pistonstickybase","piston sticky base");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("player","player");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("poison","poison");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("poisonouspotato","poisonous potato");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pork","pork");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("portal","portal");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("potato","potato");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("potatoitem","potato item");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("potion","potion");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("poweredminecart","powered minecart");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("poweredrail","powered rail");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("primedtnt","primed tnt");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("projectile","projectile");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pumpkin","pumpkin");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pumpkinpie","pumpkin pie");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pumpkinseeds","pumpkin seeds");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("pumpkinstem","pumpkin stem");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("quartz","quartz");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("quartzblock","quartz block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("quartzblock_0"," quartz block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("quartzblock_1"," quartz block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("quartzblock_2"," quartz block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("quartzore","quartz ore");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("quartzstairs","quartz stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("rails","rails");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("rawbeef","raw beef");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("rawchicken","raw chicken");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("rawfish","raw fish");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record10","record 10");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record11","record 11");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record12","record 12");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record3","record 3");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record4","record 4");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record5","record 5");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record6","record 6");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record7","record 7");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record8","record 8");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("record9","record 9");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redmushroom","red mushroom");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redrose","red rose");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstone","redstone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstoneblock","redstone block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstonecomparator","redstone comparator");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstonecomparatoroff","redstone comparator off");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstonecomparatoron","redstone comparator on");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstonelampoff","redstone lamp off");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstonelampon","redstone lamp on");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstoneore","redstone ore");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstonetorchoff","redstone torch off");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstonetorchon","redstone torch on");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("redstonewire","redstone wire");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("regen","regen");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("rottenflesh","rotten flesh");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("saddle","saddle");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sand","sand");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sandstone","sandstone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sandstone_0","cracked sandstone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sandstone_1","glyphed sandstone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sandstone_2","smooth sandstone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sandstone_3"," sandstone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sandstonestairs","sandstone stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sapling","sapling");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sapling_0","oak sapling");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sapling_1","redwood sapling");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sapling_2","birch sapling");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sapling_3","jungle sapling");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("satiated","satiated");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("seeds","seeds");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("shears","shears");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sheep","sheep");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sign","sign");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("signpost","sign post");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("silverfish","silverfish");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("skeleton","skeleton");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("skull","skull");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("skullitem","skull item");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("slime","slime");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("slimeball","slime ball");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("slowness","slowness");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("smallfireball","small fireball");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("smoothbrick","smooth brick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("smoothbrick_0","stone smooth brick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("smoothbrick_1","mossy cobblestone smooth brick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("smoothbrick_2","cobblestone smooth brick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("smoothbrick_3","smooth brick smooth brick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("smoothstairs","smooth stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("snow","snow");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("snowball","snowball");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("snowblock","snow block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("snowman","snowman");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("soil","soil");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("soulsand","soul sand");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("speckledmelon","speckled melon");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("speed","speed");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("spider","spider");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("spidereye","spider eye");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("splashpotion","splash potion");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sponge","sponge");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sprucewoodstairs","spruce wood stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("squid","squid");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stainedclay","stained clay");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("starvation","starvation");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stationarylava","stationary lava");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stationarywater","stationary water");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("step","step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("step_0","stone step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("step_1","sandstone step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("step_2","wood step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("step_3","cobblestone step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("step_4","brick step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("step_5","smooth brick step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("step_6","nether brick step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("step_7","quartz block step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stick","stick");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stone","stone");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stoneaxe","stone axe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stonebutton","stone button");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stonehoe","stone hoe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stonepickaxe","stone pickaxe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stoneplate","stone plate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stonespade","stone spade");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("stonesword","stone sword");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("storageminecart","storage minecart");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("strength","strength");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("string","string");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("suffocation","suffocation");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sugar","sugar");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sugarcane","sugar cane");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sugarcaneblock","sugar cane block");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("suicide","suicide");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("sulphur","sulphur");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("thinglass","thin glass");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("thorns","thorns");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("thrownexpbottle","thrown exp bottle");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("tnt","tnt");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("torch","torch");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("trapdoor","trap door");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("trappedchest","trapped chest");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("tripwire","tripwire");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("tripwirehook","tripwire hook");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("unknown","unknown");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("villager","villager");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("vine","vine");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("void","void");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wallsign","wall sign");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("watch","watch");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("water","water");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("waterbucket","water bucket");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("waterlily","water lily");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("weakness","weakness");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("weather","weather");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("web","web");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wheat","wheat");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("witch","witch");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wither","wither");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("witherskull","wither skull");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("witherspawn","wither spawn");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wolf","wolf");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wood","wood");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wood_0","oak wood");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wood_1","redwood wood");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wood_2","birch wood");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wood_3","jungle wood");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodaxe","wood axe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodbutton","wood button");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wooddoor","wood door");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wooddoublestep","wood double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wooddoublestep_0","oak wood double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wooddoublestep_1","redwood wood double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wooddoublestep_2","birch wood double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wooddoublestep_3","jungle wood double step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodendoor","wooden door");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodhoe","wood hoe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodpickaxe","wood pickaxe");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodplate","wood plate");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodspade","wood spade");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodstairs","wood stairs");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodstep","wood step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodstep_0","oak wood step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodstep_1","redwood wood step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodstep_2","birch wood step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodstep_3","jungle wood step");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("woodsword","wood sword");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool","wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_0","white wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_1","orange wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_10","purple wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_11","blue wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_12","brown wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_13","green wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_14","red wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_15","black wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_2","magenta wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_3","light blue wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_4","yellow wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_5","lime wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_6","pink wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_7","gray wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_8","silver wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("wool_9","cyan wool");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("workbench","workbench");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("writtenbook","written book");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("yellowflower","yellow flower");
INSERT IGNORE INTO ${PREFIX}_statistic (statistic,name) VALUES ("zombie","zombie");