INSERT IGNORE INTO ${PREFIX}_domain (domain) VALUES ('default');
INSERT IGNORE INTO ${PREFIX}_world (world,name) VALUES ('__global__','Global');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cooked fish','cookedfish_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cooked fish','cookedfish_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cooked fish','cookedfish_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cooked fish','cookedfish_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('piston base','pistonbase');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('birch wood stairs','birchwoodstairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leather chestplate','leatherchestplate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('raw fish','rawfish_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('raw fish','rawfish_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('raw fish','rawfish_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('raw fish','rawfish_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('piston moving piece','pistonmovingpiece');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cooked chicken','cookedchicken');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_13');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_14');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_15');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('spider','spider');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone hoe','stonehoe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_10');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_11');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone torch off','redstonetorchoff');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_12');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ender portal frame','enderportalframe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('torch','torch');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jungle log','log_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('birch log','log_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redwood log','log_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('golden apple','goldenapple');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('generic log','log_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('trap door','trapdoor');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond axe','diamondaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('slime ball','slimeball');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('quartz ore','quartzore');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cauldron','cauldron');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('magic','magic');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('baked potato','bakedpotato');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone spade','stonespade');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('clay brick','claybrick');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hay block','hayblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('item frame','itemframe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('quartz','quartz');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('air','air');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_13');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_12');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_15');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ender signal','endersignal');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_14');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('magic regen','magicregen');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron hoe','ironhoe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('carrot','carrot');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold record','goldrecord');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron door','irondoor');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('melon seeds','melonseeds');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('chainmail helmet','chainmailhelmet');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ender portal','enderportal');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron chestplate','ironchestplate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('command minecart','commandminecart');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leash hitch','leashhitch');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('glowstone','glowstone');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone torch on','redstonetorchon');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron sword','ironsword');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('map','map');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('generic wood step','woodstep_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sheep','sheep');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redwood wood step','woodstep_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('acacia stairs','acaciastairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('birch wood step','woodstep_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jungle wood step','woodstep_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('painting','painting');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood double step','doublestep_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cobblestone double step','doublestep_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sand','sand');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold sword','goldsword');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brick double step','doublestep_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('smooth_brick double step','doublestep_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('nether_brick double step','doublestep_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('quartz_block double step','doublestep_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bookshelf','bookshelf');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('web','web');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron block','ironblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('boat','boat');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fire','fire');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('snow block','snowblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron fence','ironfence');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cocoa','cocoa');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('crops','crops');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sandstone double step','doublestep_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone double step','doublestep_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('smooth brick','smoothbrick');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('nether star','netherstar');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('player','player');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('rails','rails');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone','stone');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('blaze powder','blazepowder');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('falling block','fallingblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond ore','diamondore');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('chainmail leggings','chainmailleggings');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('witch','witch');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron helmet','ironhelmet');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brick stairs','brickstairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('powered rail','poweredrail');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone lamp off','redstonelampoff');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('pumpkin','pumpkin');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('watch','watch');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ender crystal','endercrystal');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sign','sign');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('weakness','weakness');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leash','leash');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('saddle','saddle');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose_8');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold ingot','goldingot');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('trapped chest','trappedchest');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fire tick','firetick');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diode','diode');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('log flower pot','flowerpot_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('log flower pot','flowerpot_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('packed ice','packedice');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brown_mushroom flower pot','flowerpot_8');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red_mushroom flower pot','flowerpot_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cactus flower pot','flowerpot_9');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('magma cube','magmacube');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('horse','horse');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold pickaxe','goldpickaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hopper minecart','hopperminecart');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('blaze','blaze');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dark oak stairs','darkoakstairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron plate','ironplate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('piston extension','pistonextension');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond sword','diamondsword');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('exp bottle','expbottle');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('primed tnt','primedtnt');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('water lily','waterlily');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sponge','sponge');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('carrot item','carrotitem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('explosive minecart','explosiveminecart');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ice','ice');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('coal','coal');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cave spider','cavespider');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('netherrack','netherrack');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('flower pot','flowerpot_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red_rose flower pot','flowerpot_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('quartz block','quartzblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('yellow_flower flower pot','flowerpot_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('log flower pot','flowerpot_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('log flower pot','flowerpot_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('speed','speed');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('daylight detector','daylightdetector');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('starvation','starvation');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('tripwire','tripwire');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dead_bush flower pot','flowerpot_10');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('long_grass flower pot','flowerpot_11');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diode block off','diodeblockoff');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('flower pot','flowerpot_12');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('burning furnace','burningfurnace');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('flower pot','flowerpot_13');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ink sack','inksack');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone block','redstoneblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bow','bow');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('pumpkin pie','pumpkinpie');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('coal block','coalblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('minecart','minecart');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cooked beef','cookedbeef');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold plate','goldplate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ender dragon','enderdragon');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('suffocation','suffocation');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('quartz stairs','quartzstairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sandstone stairs','sandstonestairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('slime','slime');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('emerald','emerald');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bread','bread');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('entity attack','entityattack');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('workbench','workbench');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('mossy cobblestone','mossycobblestone');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('coal coal','coal_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('charcoal coal','coal_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('vine','vine');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('pumpkin stem','pumpkinstem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('melon','melon');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('small fireball','smallfireball');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('note block','noteblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron axe','ironaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bat','bat');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('coal ore','coalore');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('clay ball','clayball');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('silverfish','silverfish');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold nugget','goldnugget');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fishing rod','fishingrod');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('block explosion','blockexplosion');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('flower pot item','flowerpotitem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('pig zombie','pigzombie');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('shears','shears');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('monster eggs','monstereggs_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('lime ink sack','inksack_10');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_9');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('monster eggs','monstereggs_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('yellow ink sack','inksack_11');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_8');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red rose','redrose');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('potato item','potatoitem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('grilled pork','grilledpork');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('monster eggs','monstereggs_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('orange ink sack','inksack_14');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('white ink sack','inksack_15');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood door','wooddoor');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('monster eggs','monstereggs_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('light_blue ink sack','inksack_12');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('magenta ink sack','inksack_13');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('chicken','chicken');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('melting','melting');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond helmet','diamondhelmet');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('nether stalk','netherstalk');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('regen','regen');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone ore','redstoneore');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood plate','woodplate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond spade','diamondspade');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('smooth stairs','smoothstairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('water bucket','waterbucket');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('water','water');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cake block','cakeblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leaves 2','leaves2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('eye of ender','eyeofender');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('void','void');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('unknown','unknown');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('water breathing','waterbreathing');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('complex part','complexpart');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 9','record9');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 3','record3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('golden carrot','goldencarrot');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 4','record4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold barding','goldbarding');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 7','record7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 8','record8');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('written book','writtenbook');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 5','record5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 6','record6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('green ink sack','inksack_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red ink sack','inksack_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('activator rail','activatorrail');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('black ink sack','inksack_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron ore','ironore');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leather helmet','leatherhelmet');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('firework charge','fireworkcharge');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('carpet','carpet');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('melon stem','melonstem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('huge mushroom 2','hugemushroom2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('huge mushroom 1','hugemushroom1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('rotten flesh','rottenflesh');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('splash potion','splashpotion');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('flint','flint');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('pink ink sack','inksack_9');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ender stone','enderstone');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('silver ink sack','inksack_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('thorns','thorns');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gray ink sack','inksack_8');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('purple ink sack','inksack_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dirt','dirt');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cyan ink sack','inksack_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('lever','lever');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brown ink sack','inksack_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('blue ink sack','inksack_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold ore','goldore');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('minecart chest','minecartchest');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bed','bed');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('minecart furnace','minecartfurnace');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone comparator','redstonecomparator');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_9');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('double step','doublestep');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone pickaxe','stonepickaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_8');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cooked fish','cookedfish');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('glowing redstone ore','glowingredstoneore');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('apple','apple');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('tripwire hook','tripwirehook');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('blaze rod','blazerod');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('pumpkin seeds','pumpkinseeds');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('instant heal','instantheal');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stick','stick');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cobblestone smooth brick','smoothbrick_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('smooth_brick smooth brick','smoothbrick_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('firework','firework');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone smooth brick','smoothbrick_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('mossy_cobblestone smooth brick','smoothbrick_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stationary lava','stationarylava');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('enderman','enderman');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('chest','chest');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_10');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass pane','stainedglasspane_11');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jungle leaves','leaves_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('birch leaves','leaves_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redwood leaves','leaves_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('generic leaves','leaves_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold axe','goldaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('speckled melon','speckledmelon');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond','diamond');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('potion','potion');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('lapis block','lapisblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ghast tear','ghasttear');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('lava bucket','lavabucket');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sugar cane block','sugarcaneblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained glass','stainedglass');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('chainmail chestplate','chainmailchestplate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('creeper','creeper');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('pig','pig');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wooden door','woodendoor');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ghast','ghast');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('lava','lava');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brewing stand item','brewingstanditem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone','redstone');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('milk bucket','milkbucket');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('glowstone dust','glowstonedust');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('eating','eating');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('enchanted book','enchantedbook');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sign post','signpost');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('step','step');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('flower pot','flowerpot');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone lamp on','redstonelampon');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sugar','sugar');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone button','stonebutton');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood','wood');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('enchantment table','enchantmenttable');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('arrow','arrow');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond pickaxe','diamondpickaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('villager','villager');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fermented spider eye','fermentedspidereye');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond barding','diamondbarding');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('storage minecart','storageminecart');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('soul sand','soulsand');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold chestplate','goldchestplate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('snow','snow');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stationary water','stationarywater');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diode block on','diodeblockon');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wool','wool');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('suicide','suicide');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dragon egg','dragonegg');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood sword','woodsword');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond hoe','diamondhoe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('snowball','snowball');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ender chest','enderchest');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leather leggings','leatherleggings');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('double plant','doubleplant_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('log','log');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('double plant','doubleplant_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('long grass','longgrass_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cookie','cookie');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('double plant','doubleplant_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('double plant','doubleplant_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('normal long grass','longgrass_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('double plant','doubleplant_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fern_like long grass','longgrass_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dead long grass','longgrass_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('double plant','doubleplant_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('detector rail','detectorrail');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dropper','dropper');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('empty map','emptymap');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bucket','bucket');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bed block','bedblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('monster egg','monsteregg');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gravel','gravel');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('nether fence','netherfence');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond block','diamondblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('raw chicken','rawchicken');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('name tag','nametag');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('log 2','log2_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron spade','ironspade');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('furnace','furnace');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood axe','woodaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('seeds','seeds');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('projectile','projectile');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron golem','irongolem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron door block','irondoorblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold hoe','goldhoe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone axe','stoneaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('log 2','log2_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond chestplate','diamondchestplate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red mushroom','redmushroom');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone wire','redstonewire');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('string','string');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone plate','stoneplate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wall sign','wallsign');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cobble wall','cobblewall');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sulphur','sulphur');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cow','cow');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('experience orb','experienceorb');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold leggings','goldleggings');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('yellow flower','yellowflower');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wither','wither');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('obsidian','obsidian');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('poisonous potato','poisonouspotato');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_11');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('thrown exp bottle','thrownexpbottle');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_10');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('slowness','slowness');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('locked chest','lockedchest');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('invisibility','invisibility');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_15');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cauldron item','cauldronitem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_14');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leather boots','leatherboots');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leather','leather');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_13');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_12');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron ingot','ironingot');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('poison','poison');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('thin glass','thinglass');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron leggings','ironleggings');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('lightning','lightning');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('chainmail boots','chainmailboots');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond leggings','diamondleggings');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cobblestone stairs','cobblestonestairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('tnt','tnt');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood double step','wooddoublestep');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone comparator off','redstonecomparatoroff');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('monster eggs','monstereggs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wither spawn','witherspawn');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brick','brick');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sandstone','sandstone');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('skull item','skullitem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('nether brick stairs','netherbrickstairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('compass','compass');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jukebox','jukebox');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('instant damage','instantdamage');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('emerald block','emeraldblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('nether brick','netherbrick');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('minecart tnt','minecarttnt');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ladder','ladder');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bowl','bowl');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wither skull','witherskull');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('strength','strength');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dirt','dirt_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('diamond boots','diamondboots');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dirt','dirt_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fire resistance','fireresistance');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dirt','dirt_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dirt','dirt_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('purple wool','wool_10');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('blue wool','wool_11');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('quartz block','quartzblock_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brown wool','wool_12');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('quartz block','quartzblock_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('green wool','wool_13');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('quartz block','quartzblock_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('red wool','wool_14');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wolf','wolf');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('black wool','wool_15');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('spruce wood stairs','sprucewoodstairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ender pearl','enderpearl');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('potato','potato');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('giant','giant');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('satiated','satiated');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 11','record11');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_8');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 10','record10');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_9');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('record 12','record12');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('raw fish','rawfish');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leaves','leaves');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('feather','feather');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hopper','hopper');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('spider eye','spidereye');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('mushroom soup','mushroomsoup');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('weather','weather');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('entity explosion','entityexplosion');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brown mushroom','brownmushroom');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('grass','grass');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('powered minecart','poweredminecart');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redstone comparator on','redstonecomparatoron');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fence','fence');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('minecart mob spawner','minecartmobspawner');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('melon block','melonblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('carrot stick','carrotstick');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron barding','ironbarding');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('mycel','mycel');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('raw beef','rawbeef');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron pickaxe','ironpickaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dead bush','deadbush');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('contact','contact');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('zombie','zombie');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold helmet','goldhelmet');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('command','command');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dispenser','dispenser');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood step','woodstep');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('drowning','drowning');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('piston sticky base','pistonstickybase');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bedrock','bedrock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jack o lantern','jackolantern');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jungle sapling','sapling_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('anvil','anvil');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('generic sapling','sapling_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jungle sapling','sapling_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('birch sapling','sapling_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('quartz_block step','step_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redwood sapling','sapling_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('generic sapling','sapling_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('smooth_brick step','step_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('nether_brick step','step_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('birch sapling','sapling_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cobblestone step','step_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redwood sapling','sapling_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brick step','step_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fall','fall');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('beacon','beacon');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cactus','cactus');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leaves 2','leaves2_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redwood wood','wood_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('generic wood','wood_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone step','step_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sandstone step','step_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood step','step_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('nether brick item','netherbrickitem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('egg','egg');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('leaves 2','leaves2_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood hoe','woodhoe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('skull','skull');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('minecart command','minecartcommand');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('nether warts','netherwarts');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jungle wood stairs','junglewoodstairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('glass bottle','glassbottle');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cobblestone','cobblestone');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('night vision','nightvision');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('dropped item','droppeditem');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('custom','custom');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('glyphed sandstone','sandstone_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cracked sandstone','sandstone_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood stairs','woodstairs');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cake','cake');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('brewing stand','brewingstand');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sandstone','sandstone_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('mushroom cow','mushroomcow');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('portal','portal');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('smooth sandstone','sandstone_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('log 2','log2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('double plant','doubleplant');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood pickaxe','woodpickaxe');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('minecart hopper','minecarthopper');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood spade','woodspade');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('pork','pork');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('birch wood','wood_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jungle wood','wood_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('generic wood','wood_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redwood wood','wood_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('birch wood','wood_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jungle wood','wood_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('soil','soil');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('clay','clay');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold block','goldblock');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('ocelot','ocelot');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('paper','paper');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('skeleton','skeleton');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wood button','woodbutton');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sugar cane','sugarcane');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('silver wool','wool_8');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('cyan wool','wool_9');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold boots','goldboots');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('pink wool','wool_6');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('long grass','longgrass');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gray wool','wool_7');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stone sword','stonesword');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('yellow wool','wool_4');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('lime wool','wool_5');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('magenta wool','wool_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('light_blue wool','wool_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('bone','bone');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('white wool','wool_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('glass','glass');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('orange wool','wool_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('gold spade','goldspade');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fishing hook','fishinghook');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('wheat','wheat');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('book and quill','bookandquill');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fence gate','fencegate');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('generic wood double step','wooddoublestep_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('flint and steel','flintandsteel');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('sapling','sapling');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('mob spawner','mobspawner');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('jungle wood double step','wooddoublestep_3');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('redwood wood double step','wooddoublestep_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('squid','squid');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('birch wood double step','wooddoublestep_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_1');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_2');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('hard clay','hardclay_0');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('stained clay','stainedclay');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('lapis ore','lapisore');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('magma cream','magmacream');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('emerald ore','emeraldore');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('book','book');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('green record','greenrecord');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('snowman','snowman');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('iron boots','ironboots');
INSERT INGORE INTO ${PREFIX}_statistic (`name`,`statistic`) VALUES('fireball','fireball');