UPDATE ${PREFIX}_statistic SET `name`="activator rail" WHERE `statistic`="activatorrail" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="air" WHERE `statistic`="air" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="anvil" WHERE `statistic`="anvil" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="apple" WHERE `statistic`="apple" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="arrow" WHERE `statistic`="arrow" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="baked potato" WHERE `statistic`="bakedpotato" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bat" WHERE `statistic`="bat" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="beacon" WHERE `statistic`="beacon" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bed" WHERE `statistic`="bed" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bed block" WHERE `statistic`="bedblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bedrock" WHERE `statistic`="bedrock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="birch wood stairs" WHERE `statistic`="birchwoodstairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="blaze" WHERE `statistic`="blaze" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="blaze powder" WHERE `statistic`="blazepowder" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="blaze rod" WHERE `statistic`="blazerod" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="block explosion" WHERE `statistic`="blockexplosion" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="boat" WHERE `statistic`="boat" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bone" WHERE `statistic`="bone" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="book" WHERE `statistic`="book" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="book and quill" WHERE `statistic`="bookandquill" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bookshelf" WHERE `statistic`="bookshelf" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bow" WHERE `statistic`="bow" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bowl" WHERE `statistic`="bowl" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bread" WHERE `statistic`="bread" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="brewing stand" WHERE `statistic`="brewingstand" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="brewing stand item" WHERE `statistic`="brewingstanditem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="brick" WHERE `statistic`="brick" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="brick stairs" WHERE `statistic`="brickstairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="brown mushroom" WHERE `statistic`="brownmushroom" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="bucket" WHERE `statistic`="bucket" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="burning furnace" WHERE `statistic`="burningfurnace" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cactus" WHERE `statistic`="cactus" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cake" WHERE `statistic`="cake" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cake block" WHERE `statistic`="cakeblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="carrot" WHERE `statistic`="carrot" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="carrot item" WHERE `statistic`="carrotitem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="carrot stick" WHERE `statistic`="carrotstick" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cauldron" WHERE `statistic`="cauldron" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cauldron item" WHERE `statistic`="cauldronitem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cave spider" WHERE `statistic`="cavespider" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="chainmail boots" WHERE `statistic`="chainmailboots" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="chainmail chestplate" WHERE `statistic`="chainmailchestplate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="chainmail helmet" WHERE `statistic`="chainmailhelmet" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="chainmail leggings" WHERE `statistic`="chainmailleggings" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="chest" WHERE `statistic`="chest" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="chicken" WHERE `statistic`="chicken" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="clay" WHERE `statistic`="clay" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="clay ball" WHERE `statistic`="clayball" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="clay brick" WHERE `statistic`="claybrick" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="coal" WHERE `statistic`="coal" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="coal coal" WHERE `statistic`="coal_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="charcoal coal" WHERE `statistic`="coal_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="coal ore" WHERE `statistic`="coalore" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cobblestone" WHERE `statistic`="cobblestone" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cobblestone stairs" WHERE `statistic`="cobblestonestairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cobble wall" WHERE `statistic`="cobblewall" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cocoa" WHERE `statistic`="cocoa" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="command" WHERE `statistic`="command" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="compass" WHERE `statistic`="compass" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="complex part" WHERE `statistic`="complexpart" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="contact" WHERE `statistic`="contact" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cooked beef" WHERE `statistic`="cookedbeef" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cooked chicken" WHERE `statistic`="cookedchicken" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cooked fish" WHERE `statistic`="cookedfish" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cookie" WHERE `statistic`="cookie" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cow" WHERE `statistic`="cow" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="creeper" WHERE `statistic`="creeper" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="crops" WHERE `statistic`="crops" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="custom" WHERE `statistic`="custom" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="daylight detector" WHERE `statistic`="daylightdetector" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="dead bush" WHERE `statistic`="deadbush" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="detector rail" WHERE `statistic`="detectorrail" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond" WHERE `statistic`="diamond" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond axe" WHERE `statistic`="diamondaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond block" WHERE `statistic`="diamondblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond boots" WHERE `statistic`="diamondboots" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond chestplate" WHERE `statistic`="diamondchestplate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond helmet" WHERE `statistic`="diamondhelmet" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond hoe" WHERE `statistic`="diamondhoe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond leggings" WHERE `statistic`="diamondleggings" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond ore" WHERE `statistic`="diamondore" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond pickaxe" WHERE `statistic`="diamondpickaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond spade" WHERE `statistic`="diamondspade" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diamond sword" WHERE `statistic`="diamondsword" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diode" WHERE `statistic`="diode" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diode block off" WHERE `statistic`="diodeblockoff" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="diode block on" WHERE `statistic`="diodeblockon" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="dirt" WHERE `statistic`="dirt" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="dispenser" WHERE `statistic`="dispenser" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="double step" WHERE `statistic`="doublestep" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone double step" WHERE `statistic`="doublestep_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sandstone double step" WHERE `statistic`="doublestep_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood double step" WHERE `statistic`="doublestep_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cobblestone double step" WHERE `statistic`="doublestep_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="brick double step" WHERE `statistic`="doublestep_4" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="smooth brick double step" WHERE `statistic`="doublestep_5" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone double step" WHERE `statistic`="doublestep_6" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone double step" WHERE `statistic`="doublestep_7" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="dragon egg" WHERE `statistic`="dragonegg" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="dropped item" WHERE `statistic`="droppeditem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="dropper" WHERE `statistic`="dropper" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="drowning" WHERE `statistic`="drowning" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="eating" WHERE `statistic`="eating" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="egg" WHERE `statistic`="egg" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="emerald" WHERE `statistic`="emerald" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="emerald block" WHERE `statistic`="emeraldblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="emerald ore" WHERE `statistic`="emeraldore" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="empty map" WHERE `statistic`="emptymap" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="enchanted book" WHERE `statistic`="enchantedbook" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="enchantment table" WHERE `statistic`="enchantmenttable" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ender chest" WHERE `statistic`="enderchest" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ender crystal" WHERE `statistic`="endercrystal" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ender dragon" WHERE `statistic`="enderdragon" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="enderman" WHERE `statistic`="enderman" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ender pearl" WHERE `statistic`="enderpearl" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ender portal" WHERE `statistic`="enderportal" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ender portal frame" WHERE `statistic`="enderportalframe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ender signal" WHERE `statistic`="endersignal" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ender stone" WHERE `statistic`="enderstone" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="entity attack" WHERE `statistic`="entityattack" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="entity explosion" WHERE `statistic`="entityexplosion" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="exp bottle" WHERE `statistic`="expbottle" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="experience orb" WHERE `statistic`="experienceorb" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="explosive minecart" WHERE `statistic`="explosiveminecart" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="eye of ender" WHERE `statistic`="eyeofender" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fall" WHERE `statistic`="fall" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="falling block" WHERE `statistic`="fallingblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="feather" WHERE `statistic`="feather" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fence" WHERE `statistic`="fence" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fence gate" WHERE `statistic`="fencegate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fermented spider eye" WHERE `statistic`="fermentedspidereye" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fire" WHERE `statistic`="fire" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fireball" WHERE `statistic`="fireball" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fire resistance" WHERE `statistic`="fireresistance" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fire tick" WHERE `statistic`="firetick" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="firework" WHERE `statistic`="firework" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="firework charge" WHERE `statistic`="fireworkcharge" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fishing hook" WHERE `statistic`="fishinghook" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fishing rod" WHERE `statistic`="fishingrod" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="flint" WHERE `statistic`="flint" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="flint and steel" WHERE `statistic`="flintandsteel" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="flower pot" WHERE `statistic`="flowerpot" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" flower pot" WHERE `statistic`="flowerpot_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="flower pot item" WHERE `statistic`="flowerpotitem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="furnace" WHERE `statistic`="furnace" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ghast" WHERE `statistic`="ghast" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ghast tear" WHERE `statistic`="ghasttear" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="giant" WHERE `statistic`="giant" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="glass" WHERE `statistic`="glass" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="glass bottle" WHERE `statistic`="glassbottle" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="glowing redstone ore" WHERE `statistic`="glowingredstoneore" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="glowstone" WHERE `statistic`="glowstone" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="glowstone dust" WHERE `statistic`="glowstonedust" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold axe" WHERE `statistic`="goldaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold block" WHERE `statistic`="goldblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold boots" WHERE `statistic`="goldboots" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold chestplate" WHERE `statistic`="goldchestplate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="golden apple" WHERE `statistic`="goldenapple" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="golden carrot" WHERE `statistic`="goldencarrot" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold helmet" WHERE `statistic`="goldhelmet" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold hoe" WHERE `statistic`="goldhoe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold ingot" WHERE `statistic`="goldingot" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold leggings" WHERE `statistic`="goldleggings" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold nugget" WHERE `statistic`="goldnugget" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold ore" WHERE `statistic`="goldore" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold pickaxe" WHERE `statistic`="goldpickaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold plate" WHERE `statistic`="goldplate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold record" WHERE `statistic`="goldrecord" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold spade" WHERE `statistic`="goldspade" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gold sword" WHERE `statistic`="goldsword" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="grass" WHERE `statistic`="grass" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="gravel" WHERE `statistic`="gravel" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="green record" WHERE `statistic`="greenrecord" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="grilled pork" WHERE `statistic`="grilledpork" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="hopper" WHERE `statistic`="hopper" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="hopper minecart" WHERE `statistic`="hopperminecart" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="huge mushroom 1" WHERE `statistic`="hugemushroom1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="huge mushroom 2" WHERE `statistic`="hugemushroom2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ice" WHERE `statistic`="ice" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ink sack" WHERE `statistic`="inksack" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="black ink sack" WHERE `statistic`="inksack_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="instant damage" WHERE `statistic`="instantdamage" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="instant heal" WHERE `statistic`="instantheal" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="invisibility" WHERE `statistic`="invisibility" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron axe" WHERE `statistic`="ironaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron block" WHERE `statistic`="ironblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron boots" WHERE `statistic`="ironboots" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron chestplate" WHERE `statistic`="ironchestplate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron door" WHERE `statistic`="irondoor" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron door block" WHERE `statistic`="irondoorblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron fence" WHERE `statistic`="ironfence" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron golem" WHERE `statistic`="irongolem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron helmet" WHERE `statistic`="ironhelmet" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron hoe" WHERE `statistic`="ironhoe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron ingot" WHERE `statistic`="ironingot" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron leggings" WHERE `statistic`="ironleggings" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron ore" WHERE `statistic`="ironore" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron pickaxe" WHERE `statistic`="ironpickaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron plate" WHERE `statistic`="ironplate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron spade" WHERE `statistic`="ironspade" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="iron sword" WHERE `statistic`="ironsword" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="item frame" WHERE `statistic`="itemframe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="jack o lantern" WHERE `statistic`="jackolantern" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="jukebox" WHERE `statistic`="jukebox" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="jungle wood stairs" WHERE `statistic`="junglewoodstairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ladder" WHERE `statistic`="ladder" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="lapis block" WHERE `statistic`="lapisblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="lapis ore" WHERE `statistic`="lapisore" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="lava" WHERE `statistic`="lava" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="lava bucket" WHERE `statistic`="lavabucket" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="leather" WHERE `statistic`="leather" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="leather boots" WHERE `statistic`="leatherboots" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="leather chestplate" WHERE `statistic`="leatherchestplate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="leather helmet" WHERE `statistic`="leatherhelmet" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="leather leggings" WHERE `statistic`="leatherleggings" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="leaves" WHERE `statistic`="leaves" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="oak leaves" WHERE `statistic`="leaves_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redwood leaves" WHERE `statistic`="leaves_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="birch leaves" WHERE `statistic`="leaves_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="jungle leaves" WHERE `statistic`="leaves_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="lever" WHERE `statistic`="lever" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="lightning" WHERE `statistic`="lightning" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="locked chest" WHERE `statistic`="lockedchest" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="log" WHERE `statistic`="log" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="oak log" WHERE `statistic`="log_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redwood log" WHERE `statistic`="log_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="birch log" WHERE `statistic`="log_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="jungle log" WHERE `statistic`="log_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="long grass" WHERE `statistic`="longgrass" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="dead long grass" WHERE `statistic`="longgrass_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="normal long grass" WHERE `statistic`="longgrass_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="fern like long grass" WHERE `statistic`="longgrass_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" long grass" WHERE `statistic`="longgrass_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="magic" WHERE `statistic`="magic" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="magic regen" WHERE `statistic`="magicregen" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="magma cream" WHERE `statistic`="magmacream" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="magma cube" WHERE `statistic`="magmacube" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="map" WHERE `statistic`="map" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="melon" WHERE `statistic`="melon" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="melon block" WHERE `statistic`="melonblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="melon seeds" WHERE `statistic`="melonseeds" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="melon stem" WHERE `statistic`="melonstem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="melting" WHERE `statistic`="melting" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="milk bucket" WHERE `statistic`="milkbucket" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="minecart" WHERE `statistic`="minecart" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="minecart chest" WHERE `statistic`="minecartchest" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="minecart furnace" WHERE `statistic`="minecartfurnace" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="minecart hopper" WHERE `statistic`="minecarthopper" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="minecart mob spawner" WHERE `statistic`="minecartmobspawner" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="minecart tnt" WHERE `statistic`="minecarttnt" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="mob spawner" WHERE `statistic`="mobspawner" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="monster egg" WHERE `statistic`="monsteregg" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="monster eggs" WHERE `statistic`="monstereggs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" monster eggs" WHERE `statistic`="monstereggs_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" monster eggs" WHERE `statistic`="monstereggs_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" monster eggs" WHERE `statistic`="monstereggs_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" monster eggs" WHERE `statistic`="monstereggs_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="mossy cobblestone" WHERE `statistic`="mossycobblestone" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="mushroom cow" WHERE `statistic`="mushroomcow" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="mushroom soup" WHERE `statistic`="mushroomsoup" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="mycel" WHERE `statistic`="mycel" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="nether brick" WHERE `statistic`="netherbrick" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="nether brick item" WHERE `statistic`="netherbrickitem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="nether brick stairs" WHERE `statistic`="netherbrickstairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="nether fence" WHERE `statistic`="netherfence" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="netherrack" WHERE `statistic`="netherrack" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="nether stalk" WHERE `statistic`="netherstalk" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="nether star" WHERE `statistic`="netherstar" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="nether warts" WHERE `statistic`="netherwarts" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="night vision" WHERE `statistic`="nightvision" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="note block" WHERE `statistic`="noteblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="obsidian" WHERE `statistic`="obsidian" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="ocelot" WHERE `statistic`="ocelot" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="painting" WHERE `statistic`="painting" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="paper" WHERE `statistic`="paper" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="pig" WHERE `statistic`="pig" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="pig zombie" WHERE `statistic`="pigzombie" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="piston base" WHERE `statistic`="pistonbase" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="piston extension" WHERE `statistic`="pistonextension" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="piston moving piece" WHERE `statistic`="pistonmovingpiece" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="piston sticky base" WHERE `statistic`="pistonstickybase" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="player" WHERE `statistic`="player" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="poison" WHERE `statistic`="poison" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="poisonous potato" WHERE `statistic`="poisonouspotato" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="pork" WHERE `statistic`="pork" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="portal" WHERE `statistic`="portal" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="potato" WHERE `statistic`="potato" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="potato item" WHERE `statistic`="potatoitem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="potion" WHERE `statistic`="potion" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="powered minecart" WHERE `statistic`="poweredminecart" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="powered rail" WHERE `statistic`="poweredrail" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="primed tnt" WHERE `statistic`="primedtnt" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="projectile" WHERE `statistic`="projectile" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="pumpkin" WHERE `statistic`="pumpkin" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="pumpkin pie" WHERE `statistic`="pumpkinpie" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="pumpkin seeds" WHERE `statistic`="pumpkinseeds" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="pumpkin stem" WHERE `statistic`="pumpkinstem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="quartz" WHERE `statistic`="quartz" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="quartz block" WHERE `statistic`="quartzblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" quartz block" WHERE `statistic`="quartzblock_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" quartz block" WHERE `statistic`="quartzblock_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" quartz block" WHERE `statistic`="quartzblock_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="quartz ore" WHERE `statistic`="quartzore" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="quartz stairs" WHERE `statistic`="quartzstairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="rails" WHERE `statistic`="rails" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="raw beef" WHERE `statistic`="rawbeef" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="raw chicken" WHERE `statistic`="rawchicken" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="raw fish" WHERE `statistic`="rawfish" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 10" WHERE `statistic`="record10" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 11" WHERE `statistic`="record11" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 12" WHERE `statistic`="record12" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 3" WHERE `statistic`="record3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 4" WHERE `statistic`="record4" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 5" WHERE `statistic`="record5" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 6" WHERE `statistic`="record6" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 7" WHERE `statistic`="record7" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 8" WHERE `statistic`="record8" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="record 9" WHERE `statistic`="record9" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="red mushroom" WHERE `statistic`="redmushroom" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="red rose" WHERE `statistic`="redrose" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone" WHERE `statistic`="redstone" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone block" WHERE `statistic`="redstoneblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone comparator" WHERE `statistic`="redstonecomparator" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone comparator off" WHERE `statistic`="redstonecomparatoroff" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone comparator on" WHERE `statistic`="redstonecomparatoron" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone lamp off" WHERE `statistic`="redstonelampoff" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone lamp on" WHERE `statistic`="redstonelampon" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone ore" WHERE `statistic`="redstoneore" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone torch off" WHERE `statistic`="redstonetorchoff" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone torch on" WHERE `statistic`="redstonetorchon" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redstone wire" WHERE `statistic`="redstonewire" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="regen" WHERE `statistic`="regen" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="rotten flesh" WHERE `statistic`="rottenflesh" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="saddle" WHERE `statistic`="saddle" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sand" WHERE `statistic`="sand" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sandstone" WHERE `statistic`="sandstone" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cracked sandstone" WHERE `statistic`="sandstone_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="glyphed sandstone" WHERE `statistic`="sandstone_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="smooth sandstone" WHERE `statistic`="sandstone_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=" sandstone" WHERE `statistic`="sandstone_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sandstone stairs" WHERE `statistic`="sandstonestairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sapling" WHERE `statistic`="sapling" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="oak sapling" WHERE `statistic`="sapling_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redwood sapling" WHERE `statistic`="sapling_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="birch sapling" WHERE `statistic`="sapling_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="jungle sapling" WHERE `statistic`="sapling_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="satiated" WHERE `statistic`="satiated" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="seeds" WHERE `statistic`="seeds" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="shears" WHERE `statistic`="shears" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sheep" WHERE `statistic`="sheep" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sign" WHERE `statistic`="sign" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sign post" WHERE `statistic`="signpost" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="silverfish" WHERE `statistic`="silverfish" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="skeleton" WHERE `statistic`="skeleton" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="skull" WHERE `statistic`="skull" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="skull item" WHERE `statistic`="skullitem" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="slime" WHERE `statistic`="slime" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="slime ball" WHERE `statistic`="slimeball" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="slowness" WHERE `statistic`="slowness" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="small fireball" WHERE `statistic`="smallfireball" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="smooth brick" WHERE `statistic`="smoothbrick" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone smooth brick" WHERE `statistic`="smoothbrick_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="mossy cobblestone smooth brick" WHERE `statistic`="smoothbrick_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cobblestone smooth brick" WHERE `statistic`="smoothbrick_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="smooth brick smooth brick" WHERE `statistic`="smoothbrick_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="smooth stairs" WHERE `statistic`="smoothstairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="snow" WHERE `statistic`="snow" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="snowball" WHERE `statistic`="snowball" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="snow block" WHERE `statistic`="snowblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="snowman" WHERE `statistic`="snowman" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="soil" WHERE `statistic`="soil" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="soul sand" WHERE `statistic`="soulsand" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="speckled melon" WHERE `statistic`="speckledmelon" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="speed" WHERE `statistic`="speed" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="spider" WHERE `statistic`="spider" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="spider eye" WHERE `statistic`="spidereye" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="splash potion" WHERE `statistic`="splashpotion" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sponge" WHERE `statistic`="sponge" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="spruce wood stairs" WHERE `statistic`="sprucewoodstairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="squid" WHERE `statistic`="squid" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="starvation" WHERE `statistic`="starvation" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stationary lava" WHERE `statistic`="stationarylava" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stationary water" WHERE `statistic`="stationarywater" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="step" WHERE `statistic`="step" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone step" WHERE `statistic`="step_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sandstone step" WHERE `statistic`="step_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood step" WHERE `statistic`="step_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="cobblestone step" WHERE `statistic`="step_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="brick step" WHERE `statistic`="step_4" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="smooth brick step" WHERE `statistic`="step_5" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone step" WHERE `statistic`="step_6" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone step" WHERE `statistic`="step_7" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stick" WHERE `statistic`="stick" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone" WHERE `statistic`="stone" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone axe" WHERE `statistic`="stoneaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone button" WHERE `statistic`="stonebutton" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone hoe" WHERE `statistic`="stonehoe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone pickaxe" WHERE `statistic`="stonepickaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone plate" WHERE `statistic`="stoneplate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone spade" WHERE `statistic`="stonespade" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="stone sword" WHERE `statistic`="stonesword" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="storage minecart" WHERE `statistic`="storageminecart" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="strength" WHERE `statistic`="strength" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="string" WHERE `statistic`="string" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="suffocation" WHERE `statistic`="suffocation" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sugar" WHERE `statistic`="sugar" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sugar cane" WHERE `statistic`="sugarcane" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sugar cane block" WHERE `statistic`="sugarcaneblock" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="suicide" WHERE `statistic`="suicide" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="sulphur" WHERE `statistic`="sulphur" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="thin glass" WHERE `statistic`="thinglass" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="thorns" WHERE `statistic`="thorns" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="thrown exp bottle" WHERE `statistic`="thrownexpbottle" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="tnt" WHERE `statistic`="tnt" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="torch" WHERE `statistic`="torch" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="trap door" WHERE `statistic`="trapdoor" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="trapped chest" WHERE `statistic`="trappedchest" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="tripwire" WHERE `statistic`="tripwire" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="tripwire hook" WHERE `statistic`="tripwirehook" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="unknown" WHERE `statistic`="unknown" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="villager" WHERE `statistic`="villager" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="vine" WHERE `statistic`="vine" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="void" WHERE `statistic`="void" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wall sign" WHERE `statistic`="wallsign" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="watch" WHERE `statistic`="watch" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="water" WHERE `statistic`="water" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="water bucket" WHERE `statistic`="waterbucket" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="water lily" WHERE `statistic`="waterlily" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="weakness" WHERE `statistic`="weakness" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="weather" WHERE `statistic`="weather" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="web" WHERE `statistic`="web" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wheat" WHERE `statistic`="wheat" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="witch" WHERE `statistic`="witch" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wither" WHERE `statistic`="wither" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wither skull" WHERE `statistic`="witherskull" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wither spawn" WHERE `statistic`="witherspawn" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wolf" WHERE `statistic`="wolf" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood" WHERE `statistic`="wood" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="oak wood" WHERE `statistic`="wood_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redwood wood" WHERE `statistic`="wood_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="birch wood" WHERE `statistic`="wood_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="jungle wood" WHERE `statistic`="wood_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood axe" WHERE `statistic`="woodaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood button" WHERE `statistic`="woodbutton" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood door" WHERE `statistic`="wooddoor" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood double step" WHERE `statistic`="wooddoublestep" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="oak wood double step" WHERE `statistic`="wooddoublestep_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redwood wood double step" WHERE `statistic`="wooddoublestep_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="birch wood double step" WHERE `statistic`="wooddoublestep_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="jungle wood double step" WHERE `statistic`="wooddoublestep_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wooden door" WHERE `statistic`="woodendoor" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood hoe" WHERE `statistic`="woodhoe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood pickaxe" WHERE `statistic`="woodpickaxe" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood plate" WHERE `statistic`="woodplate" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood spade" WHERE `statistic`="woodspade" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood stairs" WHERE `statistic`="woodstairs" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood step" WHERE `statistic`="woodstep" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="oak wood step" WHERE `statistic`="woodstep_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="redwood wood step" WHERE `statistic`="woodstep_1" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="birch wood step" WHERE `statistic`="woodstep_2" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="jungle wood step" WHERE `statistic`="woodstep_3" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wood sword" WHERE `statistic`="woodsword" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="wool" WHERE `statistic`="wool" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="white wool" WHERE `statistic`="wool_0" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="workbench" WHERE `statistic`="workbench" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="written book" WHERE `statistic`="writtenbook" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="yellow flower" WHERE `statistic`="yellowflower" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`="zombie" WHERE `statistic`="zombie" AND `name` IS NULL;
UPDATE ${PREFIX}_statistic SET `name`=`statistic` WHERE `name` is NULL;
UPDATE `${PREFIX}_category` SET `statwrapper` = '% placed'  WHERE `statwrapper` IS NULL AND `category` = "blockcreate";
UPDATE `${PREFIX}_category` SET `statwrapper` = '% mined'   WHERE `statwrapper` IS NULL AND `category` = "blockdestroy";
UPDATE `${PREFIX}_category` SET `statwrapper` = 'to %'      WHERE `statwrapper` IS NULL AND `category` = "damagedealt";
UPDATE `${PREFIX}_category` SET `statwrapper` = 'from %'    WHERE `statwrapper` IS NULL AND `category` = "damagetaken";
UPDATE `${PREFIX}_category` SET `statwrapper` = '% deaths'  WHERE `statwrapper` IS NULL AND `category` = "deaths";
UPDATE `${PREFIX}_category` SET `statwrapper` = '% kills'   WHERE `statwrapper` IS NULL AND `category` = "kills";
UPDATE `${PREFIX}_category` SET `statwrapper` = '% shots'   WHERE `statwrapper` IS NULL AND `category` = "bow";
UPDATE `${PREFIX}_category` SET `statwrapper` = '% crafted' WHERE `statwrapper` IS NULL AND `category` = "crafting";
UPDATE `${PREFIX}_category` SET `statwrapper` = '%' WHERE `statwrapper` IS NULL;
