#Migrating to yggdrasil 1.1;
#Adding metadata tables to statistics;
ALTER TABLE  `${PREFIX}_statistic` ADD  `name` CHAR( 32 );
ALTER TABLE  `${PREFIX}_statistic` ADD  `formatting` ENUM(  'none',  'timestamp',  'time' ) NOT NULL;
ALTER TABLE  `${PREFIX}_entity`    ADD  `scoreboardhide` BOOLEAN NOT NULL;
#Adding default stat names
UPDATE ${PREFIX}_statistic SET `name`="activator rail" WHERE `statistic`="activatorrail";
UPDATE ${PREFIX}_statistic SET `name`="air" WHERE `statistic`="air";
UPDATE ${PREFIX}_statistic SET `name`="anvil" WHERE `statistic`="anvil";
UPDATE ${PREFIX}_statistic SET `name`="apple" WHERE `statistic`="apple";
UPDATE ${PREFIX}_statistic SET `name`="arrow" WHERE `statistic`="arrow";
UPDATE ${PREFIX}_statistic SET `name`="baked potato" WHERE `statistic`="bakedpotato";
UPDATE ${PREFIX}_statistic SET `name`="bat" WHERE `statistic`="bat";
UPDATE ${PREFIX}_statistic SET `name`="beacon" WHERE `statistic`="beacon";
UPDATE ${PREFIX}_statistic SET `name`="bed" WHERE `statistic`="bed";
UPDATE ${PREFIX}_statistic SET `name`="bed block" WHERE `statistic`="bedblock";
UPDATE ${PREFIX}_statistic SET `name`="bedrock" WHERE `statistic`="bedrock";
UPDATE ${PREFIX}_statistic SET `name`="birch wood stairs" WHERE `statistic`="birchwoodstairs";
UPDATE ${PREFIX}_statistic SET `name`="blaze" WHERE `statistic`="blaze";
UPDATE ${PREFIX}_statistic SET `name`="blaze powder" WHERE `statistic`="blazepowder";
UPDATE ${PREFIX}_statistic SET `name`="blaze rod" WHERE `statistic`="blazerod";
UPDATE ${PREFIX}_statistic SET `name`="block explosion" WHERE `statistic`="blockexplosion";
UPDATE ${PREFIX}_statistic SET `name`="boat" WHERE `statistic`="boat";
UPDATE ${PREFIX}_statistic SET `name`="bone" WHERE `statistic`="bone";
UPDATE ${PREFIX}_statistic SET `name`="book" WHERE `statistic`="book";
UPDATE ${PREFIX}_statistic SET `name`="book and quill" WHERE `statistic`="bookandquill";
UPDATE ${PREFIX}_statistic SET `name`="bookshelf" WHERE `statistic`="bookshelf";
UPDATE ${PREFIX}_statistic SET `name`="bow" WHERE `statistic`="bow";
UPDATE ${PREFIX}_statistic SET `name`="bowl" WHERE `statistic`="bowl";
UPDATE ${PREFIX}_statistic SET `name`="bread" WHERE `statistic`="bread";
UPDATE ${PREFIX}_statistic SET `name`="brewing stand" WHERE `statistic`="brewingstand";
UPDATE ${PREFIX}_statistic SET `name`="brewing stand item" WHERE `statistic`="brewingstanditem";
UPDATE ${PREFIX}_statistic SET `name`="brick" WHERE `statistic`="brick";
UPDATE ${PREFIX}_statistic SET `name`="brick stairs" WHERE `statistic`="brickstairs";
UPDATE ${PREFIX}_statistic SET `name`="brown mushroom" WHERE `statistic`="brownmushroom";
UPDATE ${PREFIX}_statistic SET `name`="bucket" WHERE `statistic`="bucket";
UPDATE ${PREFIX}_statistic SET `name`="burning furnace" WHERE `statistic`="burningfurnace";
UPDATE ${PREFIX}_statistic SET `name`="cactus" WHERE `statistic`="cactus";
UPDATE ${PREFIX}_statistic SET `name`="cake" WHERE `statistic`="cake";
UPDATE ${PREFIX}_statistic SET `name`="cake block" WHERE `statistic`="cakeblock";
UPDATE ${PREFIX}_statistic SET `name`="carrot" WHERE `statistic`="carrot";
UPDATE ${PREFIX}_statistic SET `name`="carrot item" WHERE `statistic`="carrotitem";
UPDATE ${PREFIX}_statistic SET `name`="carrot stick" WHERE `statistic`="carrotstick";
UPDATE ${PREFIX}_statistic SET `name`="cauldron" WHERE `statistic`="cauldron";
UPDATE ${PREFIX}_statistic SET `name`="cauldron item" WHERE `statistic`="cauldronitem";
UPDATE ${PREFIX}_statistic SET `name`="cave spider" WHERE `statistic`="cavespider";
UPDATE ${PREFIX}_statistic SET `name`="chainmail boots" WHERE `statistic`="chainmailboots";
UPDATE ${PREFIX}_statistic SET `name`="chainmail chestplate" WHERE `statistic`="chainmailchestplate";
UPDATE ${PREFIX}_statistic SET `name`="chainmail helmet" WHERE `statistic`="chainmailhelmet";
UPDATE ${PREFIX}_statistic SET `name`="chainmail leggings" WHERE `statistic`="chainmailleggings";
UPDATE ${PREFIX}_statistic SET `name`="chest" WHERE `statistic`="chest";
UPDATE ${PREFIX}_statistic SET `name`="chicken" WHERE `statistic`="chicken";
UPDATE ${PREFIX}_statistic SET `name`="clay" WHERE `statistic`="clay";
UPDATE ${PREFIX}_statistic SET `name`="clay ball" WHERE `statistic`="clayball";
UPDATE ${PREFIX}_statistic SET `name`="clay brick" WHERE `statistic`="claybrick";
UPDATE ${PREFIX}_statistic SET `name`="coal" WHERE `statistic`="coal";
UPDATE ${PREFIX}_statistic SET `name`="coal coal" WHERE `statistic`="coal_0";
UPDATE ${PREFIX}_statistic SET `name`="charcoal coal" WHERE `statistic`="coal_1";
UPDATE ${PREFIX}_statistic SET `name`="coal ore" WHERE `statistic`="coalore";
UPDATE ${PREFIX}_statistic SET `name`="cobblestone" WHERE `statistic`="cobblestone";
UPDATE ${PREFIX}_statistic SET `name`="cobblestone stairs" WHERE `statistic`="cobblestonestairs";
UPDATE ${PREFIX}_statistic SET `name`="cobble wall" WHERE `statistic`="cobblewall";
UPDATE ${PREFIX}_statistic SET `name`="cocoa" WHERE `statistic`="cocoa";
UPDATE ${PREFIX}_statistic SET `name`="command" WHERE `statistic`="command";
UPDATE ${PREFIX}_statistic SET `name`="compass" WHERE `statistic`="compass";
UPDATE ${PREFIX}_statistic SET `name`="complex part" WHERE `statistic`="complexpart";
UPDATE ${PREFIX}_statistic SET `name`="contact" WHERE `statistic`="contact";
UPDATE ${PREFIX}_statistic SET `name`="cooked beef" WHERE `statistic`="cookedbeef";
UPDATE ${PREFIX}_statistic SET `name`="cooked chicken" WHERE `statistic`="cookedchicken";
UPDATE ${PREFIX}_statistic SET `name`="cooked fish" WHERE `statistic`="cookedfish";
UPDATE ${PREFIX}_statistic SET `name`="cookie" WHERE `statistic`="cookie";
UPDATE ${PREFIX}_statistic SET `name`="cow" WHERE `statistic`="cow";
UPDATE ${PREFIX}_statistic SET `name`="creeper" WHERE `statistic`="creeper";
UPDATE ${PREFIX}_statistic SET `name`="crops" WHERE `statistic`="crops";
UPDATE ${PREFIX}_statistic SET `name`="custom" WHERE `statistic`="custom";
UPDATE ${PREFIX}_statistic SET `name`="daylight detector" WHERE `statistic`="daylightdetector";
UPDATE ${PREFIX}_statistic SET `name`="dead bush" WHERE `statistic`="deadbush";
UPDATE ${PREFIX}_statistic SET `name`="detector rail" WHERE `statistic`="detectorrail";
UPDATE ${PREFIX}_statistic SET `name`="diamond" WHERE `statistic`="diamond";
UPDATE ${PREFIX}_statistic SET `name`="diamond axe" WHERE `statistic`="diamondaxe";
UPDATE ${PREFIX}_statistic SET `name`="diamond block" WHERE `statistic`="diamondblock";
UPDATE ${PREFIX}_statistic SET `name`="diamond boots" WHERE `statistic`="diamondboots";
UPDATE ${PREFIX}_statistic SET `name`="diamond chestplate" WHERE `statistic`="diamondchestplate";
UPDATE ${PREFIX}_statistic SET `name`="diamond helmet" WHERE `statistic`="diamondhelmet";
UPDATE ${PREFIX}_statistic SET `name`="diamond hoe" WHERE `statistic`="diamondhoe";
UPDATE ${PREFIX}_statistic SET `name`="diamond leggings" WHERE `statistic`="diamondleggings";
UPDATE ${PREFIX}_statistic SET `name`="diamond ore" WHERE `statistic`="diamondore";
UPDATE ${PREFIX}_statistic SET `name`="diamond pickaxe" WHERE `statistic`="diamondpickaxe";
UPDATE ${PREFIX}_statistic SET `name`="diamond spade" WHERE `statistic`="diamondspade";
UPDATE ${PREFIX}_statistic SET `name`="diamond sword" WHERE `statistic`="diamondsword";
UPDATE ${PREFIX}_statistic SET `name`="diode" WHERE `statistic`="diode";
UPDATE ${PREFIX}_statistic SET `name`="diode block off" WHERE `statistic`="diodeblockoff";
UPDATE ${PREFIX}_statistic SET `name`="diode block on" WHERE `statistic`="diodeblockon";
UPDATE ${PREFIX}_statistic SET `name`="dirt" WHERE `statistic`="dirt";
UPDATE ${PREFIX}_statistic SET `name`="dispenser" WHERE `statistic`="dispenser";
UPDATE ${PREFIX}_statistic SET `name`="double step" WHERE `statistic`="doublestep";
UPDATE ${PREFIX}_statistic SET `name`="stone double step" WHERE `statistic`="doublestep_0";
UPDATE ${PREFIX}_statistic SET `name`="sandstone double step" WHERE `statistic`="doublestep_1";
UPDATE ${PREFIX}_statistic SET `name`="wood double step" WHERE `statistic`="doublestep_2";
UPDATE ${PREFIX}_statistic SET `name`="cobblestone double step" WHERE `statistic`="doublestep_3";
UPDATE ${PREFIX}_statistic SET `name`="brick double step" WHERE `statistic`="doublestep_4";
UPDATE ${PREFIX}_statistic SET `name`="smooth brick double step" WHERE `statistic`="doublestep_5";
UPDATE ${PREFIX}_statistic SET `name`="stone double step" WHERE `statistic`="doublestep_6";
UPDATE ${PREFIX}_statistic SET `name`="stone double step" WHERE `statistic`="doublestep_7";
UPDATE ${PREFIX}_statistic SET `name`="dragon egg" WHERE `statistic`="dragonegg";
UPDATE ${PREFIX}_statistic SET `name`="dropped item" WHERE `statistic`="droppeditem";
UPDATE ${PREFIX}_statistic SET `name`="dropper" WHERE `statistic`="dropper";
UPDATE ${PREFIX}_statistic SET `name`="drowning" WHERE `statistic`="drowning";
UPDATE ${PREFIX}_statistic SET `name`="eating" WHERE `statistic`="eating";
UPDATE ${PREFIX}_statistic SET `name`="egg" WHERE `statistic`="egg";
UPDATE ${PREFIX}_statistic SET `name`="emerald" WHERE `statistic`="emerald";
UPDATE ${PREFIX}_statistic SET `name`="emerald block" WHERE `statistic`="emeraldblock";
UPDATE ${PREFIX}_statistic SET `name`="emerald ore" WHERE `statistic`="emeraldore";
UPDATE ${PREFIX}_statistic SET `name`="empty map" WHERE `statistic`="emptymap";
UPDATE ${PREFIX}_statistic SET `name`="enchanted book" WHERE `statistic`="enchantedbook";
UPDATE ${PREFIX}_statistic SET `name`="enchantment table" WHERE `statistic`="enchantmenttable";
UPDATE ${PREFIX}_statistic SET `name`="ender chest" WHERE `statistic`="enderchest";
UPDATE ${PREFIX}_statistic SET `name`="ender crystal" WHERE `statistic`="endercrystal";
UPDATE ${PREFIX}_statistic SET `name`="ender dragon" WHERE `statistic`="enderdragon";
UPDATE ${PREFIX}_statistic SET `name`="enderman" WHERE `statistic`="enderman";
UPDATE ${PREFIX}_statistic SET `name`="ender pearl" WHERE `statistic`="enderpearl";
UPDATE ${PREFIX}_statistic SET `name`="ender portal" WHERE `statistic`="enderportal";
UPDATE ${PREFIX}_statistic SET `name`="ender portal frame" WHERE `statistic`="enderportalframe";
UPDATE ${PREFIX}_statistic SET `name`="ender signal" WHERE `statistic`="endersignal";
UPDATE ${PREFIX}_statistic SET `name`="ender stone" WHERE `statistic`="enderstone";
UPDATE ${PREFIX}_statistic SET `name`="entity attack" WHERE `statistic`="entityattack";
UPDATE ${PREFIX}_statistic SET `name`="entity explosion" WHERE `statistic`="entityexplosion";
UPDATE ${PREFIX}_statistic SET `name`="exp bottle" WHERE `statistic`="expbottle";
UPDATE ${PREFIX}_statistic SET `name`="experience orb" WHERE `statistic`="experienceorb";
UPDATE ${PREFIX}_statistic SET `name`="explosive minecart" WHERE `statistic`="explosiveminecart";
UPDATE ${PREFIX}_statistic SET `name`="eye of ender" WHERE `statistic`="eyeofender";
UPDATE ${PREFIX}_statistic SET `name`="fall" WHERE `statistic`="fall";
UPDATE ${PREFIX}_statistic SET `name`="falling block" WHERE `statistic`="fallingblock";
UPDATE ${PREFIX}_statistic SET `name`="feather" WHERE `statistic`="feather";
UPDATE ${PREFIX}_statistic SET `name`="fence" WHERE `statistic`="fence";
UPDATE ${PREFIX}_statistic SET `name`="fence gate" WHERE `statistic`="fencegate";
UPDATE ${PREFIX}_statistic SET `name`="fermented spider eye" WHERE `statistic`="fermentedspidereye";
UPDATE ${PREFIX}_statistic SET `name`="fire" WHERE `statistic`="fire";
UPDATE ${PREFIX}_statistic SET `name`="fireball" WHERE `statistic`="fireball";
UPDATE ${PREFIX}_statistic SET `name`="fire resistance" WHERE `statistic`="fireresistance";
UPDATE ${PREFIX}_statistic SET `name`="fire tick" WHERE `statistic`="firetick";
UPDATE ${PREFIX}_statistic SET `name`="firework" WHERE `statistic`="firework";
UPDATE ${PREFIX}_statistic SET `name`="firework charge" WHERE `statistic`="fireworkcharge";
UPDATE ${PREFIX}_statistic SET `name`="fishing hook" WHERE `statistic`="fishinghook";
UPDATE ${PREFIX}_statistic SET `name`="fishing rod" WHERE `statistic`="fishingrod";
UPDATE ${PREFIX}_statistic SET `name`="flint" WHERE `statistic`="flint";
UPDATE ${PREFIX}_statistic SET `name`="flint and steel" WHERE `statistic`="flintandsteel";
UPDATE ${PREFIX}_statistic SET `name`="flower pot" WHERE `statistic`="flowerpot";
UPDATE ${PREFIX}_statistic SET `name`=" flower pot" WHERE `statistic`="flowerpot_0";
UPDATE ${PREFIX}_statistic SET `name`="flower pot item" WHERE `statistic`="flowerpotitem";
UPDATE ${PREFIX}_statistic SET `name`="furnace" WHERE `statistic`="furnace";
UPDATE ${PREFIX}_statistic SET `name`="ghast" WHERE `statistic`="ghast";
UPDATE ${PREFIX}_statistic SET `name`="ghast tear" WHERE `statistic`="ghasttear";
UPDATE ${PREFIX}_statistic SET `name`="giant" WHERE `statistic`="giant";
UPDATE ${PREFIX}_statistic SET `name`="glass" WHERE `statistic`="glass";
UPDATE ${PREFIX}_statistic SET `name`="glass bottle" WHERE `statistic`="glassbottle";
UPDATE ${PREFIX}_statistic SET `name`="glowing redstone ore" WHERE `statistic`="glowingredstoneore";
UPDATE ${PREFIX}_statistic SET `name`="glowstone" WHERE `statistic`="glowstone";
UPDATE ${PREFIX}_statistic SET `name`="glowstone dust" WHERE `statistic`="glowstonedust";
UPDATE ${PREFIX}_statistic SET `name`="gold axe" WHERE `statistic`="goldaxe";
UPDATE ${PREFIX}_statistic SET `name`="gold block" WHERE `statistic`="goldblock";
UPDATE ${PREFIX}_statistic SET `name`="gold boots" WHERE `statistic`="goldboots";
UPDATE ${PREFIX}_statistic SET `name`="gold chestplate" WHERE `statistic`="goldchestplate";
UPDATE ${PREFIX}_statistic SET `name`="golden apple" WHERE `statistic`="goldenapple";
UPDATE ${PREFIX}_statistic SET `name`="golden carrot" WHERE `statistic`="goldencarrot";
UPDATE ${PREFIX}_statistic SET `name`="gold helmet" WHERE `statistic`="goldhelmet";
UPDATE ${PREFIX}_statistic SET `name`="gold hoe" WHERE `statistic`="goldhoe";
UPDATE ${PREFIX}_statistic SET `name`="gold ingot" WHERE `statistic`="goldingot";
UPDATE ${PREFIX}_statistic SET `name`="gold leggings" WHERE `statistic`="goldleggings";
UPDATE ${PREFIX}_statistic SET `name`="gold nugget" WHERE `statistic`="goldnugget";
UPDATE ${PREFIX}_statistic SET `name`="gold ore" WHERE `statistic`="goldore";
UPDATE ${PREFIX}_statistic SET `name`="gold pickaxe" WHERE `statistic`="goldpickaxe";
UPDATE ${PREFIX}_statistic SET `name`="gold plate" WHERE `statistic`="goldplate";
UPDATE ${PREFIX}_statistic SET `name`="gold record" WHERE `statistic`="goldrecord";
UPDATE ${PREFIX}_statistic SET `name`="gold spade" WHERE `statistic`="goldspade";
UPDATE ${PREFIX}_statistic SET `name`="gold sword" WHERE `statistic`="goldsword";
UPDATE ${PREFIX}_statistic SET `name`="grass" WHERE `statistic`="grass";
UPDATE ${PREFIX}_statistic SET `name`="gravel" WHERE `statistic`="gravel";
UPDATE ${PREFIX}_statistic SET `name`="green record" WHERE `statistic`="greenrecord";
UPDATE ${PREFIX}_statistic SET `name`="grilled pork" WHERE `statistic`="grilledpork";
UPDATE ${PREFIX}_statistic SET `name`="hopper" WHERE `statistic`="hopper";
UPDATE ${PREFIX}_statistic SET `name`="hopper minecart" WHERE `statistic`="hopperminecart";
UPDATE ${PREFIX}_statistic SET `name`="huge mushroom 1" WHERE `statistic`="hugemushroom1";
UPDATE ${PREFIX}_statistic SET `name`="huge mushroom 2" WHERE `statistic`="hugemushroom2";
UPDATE ${PREFIX}_statistic SET `name`="ice" WHERE `statistic`="ice";
UPDATE ${PREFIX}_statistic SET `name`="ink sack" WHERE `statistic`="inksack";
UPDATE ${PREFIX}_statistic SET `name`="black ink sack" WHERE `statistic`="inksack_0";
UPDATE ${PREFIX}_statistic SET `name`="instant damage" WHERE `statistic`="instantdamage";
UPDATE ${PREFIX}_statistic SET `name`="instant heal" WHERE `statistic`="instantheal";
UPDATE ${PREFIX}_statistic SET `name`="invisibility" WHERE `statistic`="invisibility";
UPDATE ${PREFIX}_statistic SET `name`="iron axe" WHERE `statistic`="ironaxe";
UPDATE ${PREFIX}_statistic SET `name`="iron block" WHERE `statistic`="ironblock";
UPDATE ${PREFIX}_statistic SET `name`="iron boots" WHERE `statistic`="ironboots";
UPDATE ${PREFIX}_statistic SET `name`="iron chestplate" WHERE `statistic`="ironchestplate";
UPDATE ${PREFIX}_statistic SET `name`="iron door" WHERE `statistic`="irondoor";
UPDATE ${PREFIX}_statistic SET `name`="iron door block" WHERE `statistic`="irondoorblock";
UPDATE ${PREFIX}_statistic SET `name`="iron fence" WHERE `statistic`="ironfence";
UPDATE ${PREFIX}_statistic SET `name`="iron golem" WHERE `statistic`="irongolem";
UPDATE ${PREFIX}_statistic SET `name`="iron helmet" WHERE `statistic`="ironhelmet";
UPDATE ${PREFIX}_statistic SET `name`="iron hoe" WHERE `statistic`="ironhoe";
UPDATE ${PREFIX}_statistic SET `name`="iron ingot" WHERE `statistic`="ironingot";
UPDATE ${PREFIX}_statistic SET `name`="iron leggings" WHERE `statistic`="ironleggings";
UPDATE ${PREFIX}_statistic SET `name`="iron ore" WHERE `statistic`="ironore";
UPDATE ${PREFIX}_statistic SET `name`="iron pickaxe" WHERE `statistic`="ironpickaxe";
UPDATE ${PREFIX}_statistic SET `name`="iron plate" WHERE `statistic`="ironplate";
UPDATE ${PREFIX}_statistic SET `name`="iron spade" WHERE `statistic`="ironspade";
UPDATE ${PREFIX}_statistic SET `name`="iron sword" WHERE `statistic`="ironsword";
UPDATE ${PREFIX}_statistic SET `name`="item frame" WHERE `statistic`="itemframe";
UPDATE ${PREFIX}_statistic SET `name`="jack o lantern" WHERE `statistic`="jackolantern";
UPDATE ${PREFIX}_statistic SET `name`="jukebox" WHERE `statistic`="jukebox";
UPDATE ${PREFIX}_statistic SET `name`="jungle wood stairs" WHERE `statistic`="junglewoodstairs";
UPDATE ${PREFIX}_statistic SET `name`="ladder" WHERE `statistic`="ladder";
UPDATE ${PREFIX}_statistic SET `name`="lapis block" WHERE `statistic`="lapisblock";
UPDATE ${PREFIX}_statistic SET `name`="lapis ore" WHERE `statistic`="lapisore";
UPDATE ${PREFIX}_statistic SET `name`="lava" WHERE `statistic`="lava";
UPDATE ${PREFIX}_statistic SET `name`="lava bucket" WHERE `statistic`="lavabucket";
UPDATE ${PREFIX}_statistic SET `name`="leather" WHERE `statistic`="leather";
UPDATE ${PREFIX}_statistic SET `name`="leather boots" WHERE `statistic`="leatherboots";
UPDATE ${PREFIX}_statistic SET `name`="leather chestplate" WHERE `statistic`="leatherchestplate";
UPDATE ${PREFIX}_statistic SET `name`="leather helmet" WHERE `statistic`="leatherhelmet";
UPDATE ${PREFIX}_statistic SET `name`="leather leggings" WHERE `statistic`="leatherleggings";
UPDATE ${PREFIX}_statistic SET `name`="leaves" WHERE `statistic`="leaves";
UPDATE ${PREFIX}_statistic SET `name`="oak leaves" WHERE `statistic`="leaves_0";
UPDATE ${PREFIX}_statistic SET `name`="redwood leaves" WHERE `statistic`="leaves_1";
UPDATE ${PREFIX}_statistic SET `name`="birch leaves" WHERE `statistic`="leaves_2";
UPDATE ${PREFIX}_statistic SET `name`="jungle leaves" WHERE `statistic`="leaves_3";
UPDATE ${PREFIX}_statistic SET `name`="lever" WHERE `statistic`="lever";
UPDATE ${PREFIX}_statistic SET `name`="lightning" WHERE `statistic`="lightning";
UPDATE ${PREFIX}_statistic SET `name`="locked chest" WHERE `statistic`="lockedchest";
UPDATE ${PREFIX}_statistic SET `name`="log" WHERE `statistic`="log";
UPDATE ${PREFIX}_statistic SET `name`="oak log" WHERE `statistic`="log_0";
UPDATE ${PREFIX}_statistic SET `name`="redwood log" WHERE `statistic`="log_1";
UPDATE ${PREFIX}_statistic SET `name`="birch log" WHERE `statistic`="log_2";
UPDATE ${PREFIX}_statistic SET `name`="jungle log" WHERE `statistic`="log_3";
UPDATE ${PREFIX}_statistic SET `name`="long grass" WHERE `statistic`="longgrass";
UPDATE ${PREFIX}_statistic SET `name`="dead long grass" WHERE `statistic`="longgrass_0";
UPDATE ${PREFIX}_statistic SET `name`="normal long grass" WHERE `statistic`="longgrass_1";
UPDATE ${PREFIX}_statistic SET `name`="fern like long grass" WHERE `statistic`="longgrass_2";
UPDATE ${PREFIX}_statistic SET `name`=" long grass" WHERE `statistic`="longgrass_3";
UPDATE ${PREFIX}_statistic SET `name`="magic" WHERE `statistic`="magic";
UPDATE ${PREFIX}_statistic SET `name`="magic regen" WHERE `statistic`="magicregen";
UPDATE ${PREFIX}_statistic SET `name`="magma cream" WHERE `statistic`="magmacream";
UPDATE ${PREFIX}_statistic SET `name`="magma cube" WHERE `statistic`="magmacube";
UPDATE ${PREFIX}_statistic SET `name`="map" WHERE `statistic`="map";
UPDATE ${PREFIX}_statistic SET `name`="melon" WHERE `statistic`="melon";
UPDATE ${PREFIX}_statistic SET `name`="melon block" WHERE `statistic`="melonblock";
UPDATE ${PREFIX}_statistic SET `name`="melon seeds" WHERE `statistic`="melonseeds";
UPDATE ${PREFIX}_statistic SET `name`="melon stem" WHERE `statistic`="melonstem";
UPDATE ${PREFIX}_statistic SET `name`="melting" WHERE `statistic`="melting";
UPDATE ${PREFIX}_statistic SET `name`="milk bucket" WHERE `statistic`="milkbucket";
UPDATE ${PREFIX}_statistic SET `name`="minecart" WHERE `statistic`="minecart";
UPDATE ${PREFIX}_statistic SET `name`="minecart chest" WHERE `statistic`="minecartchest";
UPDATE ${PREFIX}_statistic SET `name`="minecart furnace" WHERE `statistic`="minecartfurnace";
UPDATE ${PREFIX}_statistic SET `name`="minecart hopper" WHERE `statistic`="minecarthopper";
UPDATE ${PREFIX}_statistic SET `name`="minecart mob spawner" WHERE `statistic`="minecartmobspawner";
UPDATE ${PREFIX}_statistic SET `name`="minecart tnt" WHERE `statistic`="minecarttnt";
UPDATE ${PREFIX}_statistic SET `name`="mob spawner" WHERE `statistic`="mobspawner";
UPDATE ${PREFIX}_statistic SET `name`="monster egg" WHERE `statistic`="monsteregg";
UPDATE ${PREFIX}_statistic SET `name`="monster eggs" WHERE `statistic`="monstereggs";
UPDATE ${PREFIX}_statistic SET `name`=" monster eggs" WHERE `statistic`="monstereggs_0";
UPDATE ${PREFIX}_statistic SET `name`=" monster eggs" WHERE `statistic`="monstereggs_1";
UPDATE ${PREFIX}_statistic SET `name`=" monster eggs" WHERE `statistic`="monstereggs_2";
UPDATE ${PREFIX}_statistic SET `name`=" monster eggs" WHERE `statistic`="monstereggs_3";
UPDATE ${PREFIX}_statistic SET `name`="mossy cobblestone" WHERE `statistic`="mossycobblestone";
UPDATE ${PREFIX}_statistic SET `name`="mushroom cow" WHERE `statistic`="mushroomcow";
UPDATE ${PREFIX}_statistic SET `name`="mushroom soup" WHERE `statistic`="mushroomsoup";
UPDATE ${PREFIX}_statistic SET `name`="mycel" WHERE `statistic`="mycel";
UPDATE ${PREFIX}_statistic SET `name`="nether brick" WHERE `statistic`="netherbrick";
UPDATE ${PREFIX}_statistic SET `name`="nether brick item" WHERE `statistic`="netherbrickitem";
UPDATE ${PREFIX}_statistic SET `name`="nether brick stairs" WHERE `statistic`="netherbrickstairs";
UPDATE ${PREFIX}_statistic SET `name`="nether fence" WHERE `statistic`="netherfence";
UPDATE ${PREFIX}_statistic SET `name`="netherrack" WHERE `statistic`="netherrack";
UPDATE ${PREFIX}_statistic SET `name`="nether stalk" WHERE `statistic`="netherstalk";
UPDATE ${PREFIX}_statistic SET `name`="nether star" WHERE `statistic`="netherstar";
UPDATE ${PREFIX}_statistic SET `name`="nether warts" WHERE `statistic`="netherwarts";
UPDATE ${PREFIX}_statistic SET `name`="night vision" WHERE `statistic`="nightvision";
UPDATE ${PREFIX}_statistic SET `name`="note block" WHERE `statistic`="noteblock";
UPDATE ${PREFIX}_statistic SET `name`="obsidian" WHERE `statistic`="obsidian";
UPDATE ${PREFIX}_statistic SET `name`="ocelot" WHERE `statistic`="ocelot";
UPDATE ${PREFIX}_statistic SET `name`="painting" WHERE `statistic`="painting";
UPDATE ${PREFIX}_statistic SET `name`="paper" WHERE `statistic`="paper";
UPDATE ${PREFIX}_statistic SET `name`="pig" WHERE `statistic`="pig";
UPDATE ${PREFIX}_statistic SET `name`="pig zombie" WHERE `statistic`="pigzombie";
UPDATE ${PREFIX}_statistic SET `name`="piston base" WHERE `statistic`="pistonbase";
UPDATE ${PREFIX}_statistic SET `name`="piston extension" WHERE `statistic`="pistonextension";
UPDATE ${PREFIX}_statistic SET `name`="piston moving piece" WHERE `statistic`="pistonmovingpiece";
UPDATE ${PREFIX}_statistic SET `name`="piston sticky base" WHERE `statistic`="pistonstickybase";
UPDATE ${PREFIX}_statistic SET `name`="player" WHERE `statistic`="player";
UPDATE ${PREFIX}_statistic SET `name`="poison" WHERE `statistic`="poison";
UPDATE ${PREFIX}_statistic SET `name`="poisonous potato" WHERE `statistic`="poisonouspotato";
UPDATE ${PREFIX}_statistic SET `name`="pork" WHERE `statistic`="pork";
UPDATE ${PREFIX}_statistic SET `name`="portal" WHERE `statistic`="portal";
UPDATE ${PREFIX}_statistic SET `name`="potato" WHERE `statistic`="potato";
UPDATE ${PREFIX}_statistic SET `name`="potato item" WHERE `statistic`="potatoitem";
UPDATE ${PREFIX}_statistic SET `name`="potion" WHERE `statistic`="potion";
UPDATE ${PREFIX}_statistic SET `name`="powered minecart" WHERE `statistic`="poweredminecart";
UPDATE ${PREFIX}_statistic SET `name`="powered rail" WHERE `statistic`="poweredrail";
UPDATE ${PREFIX}_statistic SET `name`="primed tnt" WHERE `statistic`="primedtnt";
UPDATE ${PREFIX}_statistic SET `name`="projectile" WHERE `statistic`="projectile";
UPDATE ${PREFIX}_statistic SET `name`="pumpkin" WHERE `statistic`="pumpkin";
UPDATE ${PREFIX}_statistic SET `name`="pumpkin pie" WHERE `statistic`="pumpkinpie";
UPDATE ${PREFIX}_statistic SET `name`="pumpkin seeds" WHERE `statistic`="pumpkinseeds";
UPDATE ${PREFIX}_statistic SET `name`="pumpkin stem" WHERE `statistic`="pumpkinstem";
UPDATE ${PREFIX}_statistic SET `name`="quartz" WHERE `statistic`="quartz";
UPDATE ${PREFIX}_statistic SET `name`="quartz block" WHERE `statistic`="quartzblock";
UPDATE ${PREFIX}_statistic SET `name`=" quartz block" WHERE `statistic`="quartzblock_0";
UPDATE ${PREFIX}_statistic SET `name`=" quartz block" WHERE `statistic`="quartzblock_1";
UPDATE ${PREFIX}_statistic SET `name`=" quartz block" WHERE `statistic`="quartzblock_2";
UPDATE ${PREFIX}_statistic SET `name`="quartz ore" WHERE `statistic`="quartzore";
UPDATE ${PREFIX}_statistic SET `name`="quartz stairs" WHERE `statistic`="quartzstairs";
UPDATE ${PREFIX}_statistic SET `name`="rails" WHERE `statistic`="rails";
UPDATE ${PREFIX}_statistic SET `name`="raw beef" WHERE `statistic`="rawbeef";
UPDATE ${PREFIX}_statistic SET `name`="raw chicken" WHERE `statistic`="rawchicken";
UPDATE ${PREFIX}_statistic SET `name`="raw fish" WHERE `statistic`="rawfish";
UPDATE ${PREFIX}_statistic SET `name`="record 10" WHERE `statistic`="record10";
UPDATE ${PREFIX}_statistic SET `name`="record 11" WHERE `statistic`="record11";
UPDATE ${PREFIX}_statistic SET `name`="record 12" WHERE `statistic`="record12";
UPDATE ${PREFIX}_statistic SET `name`="record 3" WHERE `statistic`="record3";
UPDATE ${PREFIX}_statistic SET `name`="record 4" WHERE `statistic`="record4";
UPDATE ${PREFIX}_statistic SET `name`="record 5" WHERE `statistic`="record5";
UPDATE ${PREFIX}_statistic SET `name`="record 6" WHERE `statistic`="record6";
UPDATE ${PREFIX}_statistic SET `name`="record 7" WHERE `statistic`="record7";
UPDATE ${PREFIX}_statistic SET `name`="record 8" WHERE `statistic`="record8";
UPDATE ${PREFIX}_statistic SET `name`="record 9" WHERE `statistic`="record9";
UPDATE ${PREFIX}_statistic SET `name`="red mushroom" WHERE `statistic`="redmushroom";
UPDATE ${PREFIX}_statistic SET `name`="red rose" WHERE `statistic`="redrose";
UPDATE ${PREFIX}_statistic SET `name`="redstone" WHERE `statistic`="redstone";
UPDATE ${PREFIX}_statistic SET `name`="redstone block" WHERE `statistic`="redstoneblock";
UPDATE ${PREFIX}_statistic SET `name`="redstone comparator" WHERE `statistic`="redstonecomparator";
UPDATE ${PREFIX}_statistic SET `name`="redstone comparator off" WHERE `statistic`="redstonecomparatoroff";
UPDATE ${PREFIX}_statistic SET `name`="redstone comparator on" WHERE `statistic`="redstonecomparatoron";
UPDATE ${PREFIX}_statistic SET `name`="redstone lamp off" WHERE `statistic`="redstonelampoff";
UPDATE ${PREFIX}_statistic SET `name`="redstone lamp on" WHERE `statistic`="redstonelampon";
UPDATE ${PREFIX}_statistic SET `name`="redstone ore" WHERE `statistic`="redstoneore";
UPDATE ${PREFIX}_statistic SET `name`="redstone torch off" WHERE `statistic`="redstonetorchoff";
UPDATE ${PREFIX}_statistic SET `name`="redstone torch on" WHERE `statistic`="redstonetorchon";
UPDATE ${PREFIX}_statistic SET `name`="redstone wire" WHERE `statistic`="redstonewire";
UPDATE ${PREFIX}_statistic SET `name`="regen" WHERE `statistic`="regen";
UPDATE ${PREFIX}_statistic SET `name`="rotten flesh" WHERE `statistic`="rottenflesh";
UPDATE ${PREFIX}_statistic SET `name`="saddle" WHERE `statistic`="saddle";
UPDATE ${PREFIX}_statistic SET `name`="sand" WHERE `statistic`="sand";
UPDATE ${PREFIX}_statistic SET `name`="sandstone" WHERE `statistic`="sandstone";
UPDATE ${PREFIX}_statistic SET `name`="cracked sandstone" WHERE `statistic`="sandstone_0";
UPDATE ${PREFIX}_statistic SET `name`="glyphed sandstone" WHERE `statistic`="sandstone_1";
UPDATE ${PREFIX}_statistic SET `name`="smooth sandstone" WHERE `statistic`="sandstone_2";
UPDATE ${PREFIX}_statistic SET `name`=" sandstone" WHERE `statistic`="sandstone_3";
UPDATE ${PREFIX}_statistic SET `name`="sandstone stairs" WHERE `statistic`="sandstonestairs";
UPDATE ${PREFIX}_statistic SET `name`="sapling" WHERE `statistic`="sapling";
UPDATE ${PREFIX}_statistic SET `name`="oak sapling" WHERE `statistic`="sapling_0";
UPDATE ${PREFIX}_statistic SET `name`="redwood sapling" WHERE `statistic`="sapling_1";
UPDATE ${PREFIX}_statistic SET `name`="birch sapling" WHERE `statistic`="sapling_2";
UPDATE ${PREFIX}_statistic SET `name`="jungle sapling" WHERE `statistic`="sapling_3";
UPDATE ${PREFIX}_statistic SET `name`="satiated" WHERE `statistic`="satiated";
UPDATE ${PREFIX}_statistic SET `name`="seeds" WHERE `statistic`="seeds";
UPDATE ${PREFIX}_statistic SET `name`="shears" WHERE `statistic`="shears";
UPDATE ${PREFIX}_statistic SET `name`="sheep" WHERE `statistic`="sheep";
UPDATE ${PREFIX}_statistic SET `name`="sign" WHERE `statistic`="sign";
UPDATE ${PREFIX}_statistic SET `name`="sign post" WHERE `statistic`="signpost";
UPDATE ${PREFIX}_statistic SET `name`="silverfish" WHERE `statistic`="silverfish";
UPDATE ${PREFIX}_statistic SET `name`="skeleton" WHERE `statistic`="skeleton";
UPDATE ${PREFIX}_statistic SET `name`="skull" WHERE `statistic`="skull";
UPDATE ${PREFIX}_statistic SET `name`="skull item" WHERE `statistic`="skullitem";
UPDATE ${PREFIX}_statistic SET `name`="slime" WHERE `statistic`="slime";
UPDATE ${PREFIX}_statistic SET `name`="slime ball" WHERE `statistic`="slimeball";
UPDATE ${PREFIX}_statistic SET `name`="slowness" WHERE `statistic`="slowness";
UPDATE ${PREFIX}_statistic SET `name`="small fireball" WHERE `statistic`="smallfireball";
UPDATE ${PREFIX}_statistic SET `name`="smooth brick" WHERE `statistic`="smoothbrick";
UPDATE ${PREFIX}_statistic SET `name`="stone smooth brick" WHERE `statistic`="smoothbrick_0";
UPDATE ${PREFIX}_statistic SET `name`="mossy cobblestone smooth brick" WHERE `statistic`="smoothbrick_1";
UPDATE ${PREFIX}_statistic SET `name`="cobblestone smooth brick" WHERE `statistic`="smoothbrick_2";
UPDATE ${PREFIX}_statistic SET `name`="smooth brick smooth brick" WHERE `statistic`="smoothbrick_3";
UPDATE ${PREFIX}_statistic SET `name`="smooth stairs" WHERE `statistic`="smoothstairs";
UPDATE ${PREFIX}_statistic SET `name`="snow" WHERE `statistic`="snow";
UPDATE ${PREFIX}_statistic SET `name`="snowball" WHERE `statistic`="snowball";
UPDATE ${PREFIX}_statistic SET `name`="snow block" WHERE `statistic`="snowblock";
UPDATE ${PREFIX}_statistic SET `name`="snowman" WHERE `statistic`="snowman";
UPDATE ${PREFIX}_statistic SET `name`="soil" WHERE `statistic`="soil";
UPDATE ${PREFIX}_statistic SET `name`="soul sand" WHERE `statistic`="soulsand";
UPDATE ${PREFIX}_statistic SET `name`="speckled melon" WHERE `statistic`="speckledmelon";
UPDATE ${PREFIX}_statistic SET `name`="speed" WHERE `statistic`="speed";
UPDATE ${PREFIX}_statistic SET `name`="spider" WHERE `statistic`="spider";
UPDATE ${PREFIX}_statistic SET `name`="spider eye" WHERE `statistic`="spidereye";
UPDATE ${PREFIX}_statistic SET `name`="splash potion" WHERE `statistic`="splashpotion";
UPDATE ${PREFIX}_statistic SET `name`="sponge" WHERE `statistic`="sponge";
UPDATE ${PREFIX}_statistic SET `name`="spruce wood stairs" WHERE `statistic`="sprucewoodstairs";
UPDATE ${PREFIX}_statistic SET `name`="squid" WHERE `statistic`="squid";
UPDATE ${PREFIX}_statistic SET `name`="starvation" WHERE `statistic`="starvation";
UPDATE ${PREFIX}_statistic SET `name`="stationary lava" WHERE `statistic`="stationarylava";
UPDATE ${PREFIX}_statistic SET `name`="stationary water" WHERE `statistic`="stationarywater";
UPDATE ${PREFIX}_statistic SET `name`="step" WHERE `statistic`="step";
UPDATE ${PREFIX}_statistic SET `name`="stone step" WHERE `statistic`="step_0";
UPDATE ${PREFIX}_statistic SET `name`="sandstone step" WHERE `statistic`="step_1";
UPDATE ${PREFIX}_statistic SET `name`="wood step" WHERE `statistic`="step_2";
UPDATE ${PREFIX}_statistic SET `name`="cobblestone step" WHERE `statistic`="step_3";
UPDATE ${PREFIX}_statistic SET `name`="brick step" WHERE `statistic`="step_4";
UPDATE ${PREFIX}_statistic SET `name`="smooth brick step" WHERE `statistic`="step_5";
UPDATE ${PREFIX}_statistic SET `name`="stone step" WHERE `statistic`="step_6";
UPDATE ${PREFIX}_statistic SET `name`="stone step" WHERE `statistic`="step_7";
UPDATE ${PREFIX}_statistic SET `name`="stick" WHERE `statistic`="stick";
UPDATE ${PREFIX}_statistic SET `name`="stone" WHERE `statistic`="stone";
UPDATE ${PREFIX}_statistic SET `name`="stone axe" WHERE `statistic`="stoneaxe";
UPDATE ${PREFIX}_statistic SET `name`="stone button" WHERE `statistic`="stonebutton";
UPDATE ${PREFIX}_statistic SET `name`="stone hoe" WHERE `statistic`="stonehoe";
UPDATE ${PREFIX}_statistic SET `name`="stone pickaxe" WHERE `statistic`="stonepickaxe";
UPDATE ${PREFIX}_statistic SET `name`="stone plate" WHERE `statistic`="stoneplate";
UPDATE ${PREFIX}_statistic SET `name`="stone spade" WHERE `statistic`="stonespade";
UPDATE ${PREFIX}_statistic SET `name`="stone sword" WHERE `statistic`="stonesword";
UPDATE ${PREFIX}_statistic SET `name`="storage minecart" WHERE `statistic`="storageminecart";
UPDATE ${PREFIX}_statistic SET `name`="strength" WHERE `statistic`="strength";
UPDATE ${PREFIX}_statistic SET `name`="string" WHERE `statistic`="string";
UPDATE ${PREFIX}_statistic SET `name`="suffocation" WHERE `statistic`="suffocation";
UPDATE ${PREFIX}_statistic SET `name`="sugar" WHERE `statistic`="sugar";
UPDATE ${PREFIX}_statistic SET `name`="sugar cane" WHERE `statistic`="sugarcane";
UPDATE ${PREFIX}_statistic SET `name`="sugar cane block" WHERE `statistic`="sugarcaneblock";
UPDATE ${PREFIX}_statistic SET `name`="suicide" WHERE `statistic`="suicide";
UPDATE ${PREFIX}_statistic SET `name`="sulphur" WHERE `statistic`="sulphur";
UPDATE ${PREFIX}_statistic SET `name`="thin glass" WHERE `statistic`="thinglass";
UPDATE ${PREFIX}_statistic SET `name`="thorns" WHERE `statistic`="thorns";
UPDATE ${PREFIX}_statistic SET `name`="thrown exp bottle" WHERE `statistic`="thrownexpbottle";
UPDATE ${PREFIX}_statistic SET `name`="tnt" WHERE `statistic`="tnt";
UPDATE ${PREFIX}_statistic SET `name`="torch" WHERE `statistic`="torch";
UPDATE ${PREFIX}_statistic SET `name`="trap door" WHERE `statistic`="trapdoor";
UPDATE ${PREFIX}_statistic SET `name`="trapped chest" WHERE `statistic`="trappedchest";
UPDATE ${PREFIX}_statistic SET `name`="tripwire" WHERE `statistic`="tripwire";
UPDATE ${PREFIX}_statistic SET `name`="tripwire hook" WHERE `statistic`="tripwirehook";
UPDATE ${PREFIX}_statistic SET `name`="unknown" WHERE `statistic`="unknown";
UPDATE ${PREFIX}_statistic SET `name`="villager" WHERE `statistic`="villager";
UPDATE ${PREFIX}_statistic SET `name`="vine" WHERE `statistic`="vine";
UPDATE ${PREFIX}_statistic SET `name`="void" WHERE `statistic`="void";
UPDATE ${PREFIX}_statistic SET `name`="wall sign" WHERE `statistic`="wallsign";
UPDATE ${PREFIX}_statistic SET `name`="watch" WHERE `statistic`="watch";
UPDATE ${PREFIX}_statistic SET `name`="water" WHERE `statistic`="water";
UPDATE ${PREFIX}_statistic SET `name`="water bucket" WHERE `statistic`="waterbucket";
UPDATE ${PREFIX}_statistic SET `name`="water lily" WHERE `statistic`="waterlily";
UPDATE ${PREFIX}_statistic SET `name`="weakness" WHERE `statistic`="weakness";
UPDATE ${PREFIX}_statistic SET `name`="weather" WHERE `statistic`="weather";
UPDATE ${PREFIX}_statistic SET `name`="web" WHERE `statistic`="web";
UPDATE ${PREFIX}_statistic SET `name`="wheat" WHERE `statistic`="wheat";
UPDATE ${PREFIX}_statistic SET `name`="witch" WHERE `statistic`="witch";
UPDATE ${PREFIX}_statistic SET `name`="wither" WHERE `statistic`="wither";
UPDATE ${PREFIX}_statistic SET `name`="wither skull" WHERE `statistic`="witherskull";
UPDATE ${PREFIX}_statistic SET `name`="wither spawn" WHERE `statistic`="witherspawn";
UPDATE ${PREFIX}_statistic SET `name`="wolf" WHERE `statistic`="wolf";
UPDATE ${PREFIX}_statistic SET `name`="wood" WHERE `statistic`="wood";
UPDATE ${PREFIX}_statistic SET `name`="oak wood" WHERE `statistic`="wood_0";
UPDATE ${PREFIX}_statistic SET `name`="redwood wood" WHERE `statistic`="wood_1";
UPDATE ${PREFIX}_statistic SET `name`="birch wood" WHERE `statistic`="wood_2";
UPDATE ${PREFIX}_statistic SET `name`="jungle wood" WHERE `statistic`="wood_3";
UPDATE ${PREFIX}_statistic SET `name`="wood axe" WHERE `statistic`="woodaxe";
UPDATE ${PREFIX}_statistic SET `name`="wood button" WHERE `statistic`="woodbutton";
UPDATE ${PREFIX}_statistic SET `name`="wood door" WHERE `statistic`="wooddoor";
UPDATE ${PREFIX}_statistic SET `name`="wood double step" WHERE `statistic`="wooddoublestep";
UPDATE ${PREFIX}_statistic SET `name`="oak wood double step" WHERE `statistic`="wooddoublestep_0";
UPDATE ${PREFIX}_statistic SET `name`="redwood wood double step" WHERE `statistic`="wooddoublestep_1";
UPDATE ${PREFIX}_statistic SET `name`="birch wood double step" WHERE `statistic`="wooddoublestep_2";
UPDATE ${PREFIX}_statistic SET `name`="jungle wood double step" WHERE `statistic`="wooddoublestep_3";
UPDATE ${PREFIX}_statistic SET `name`="wooden door" WHERE `statistic`="woodendoor";
UPDATE ${PREFIX}_statistic SET `name`="wood hoe" WHERE `statistic`="woodhoe";
UPDATE ${PREFIX}_statistic SET `name`="wood pickaxe" WHERE `statistic`="woodpickaxe";
UPDATE ${PREFIX}_statistic SET `name`="wood plate" WHERE `statistic`="woodplate";
UPDATE ${PREFIX}_statistic SET `name`="wood spade" WHERE `statistic`="woodspade";
UPDATE ${PREFIX}_statistic SET `name`="wood stairs" WHERE `statistic`="woodstairs";
UPDATE ${PREFIX}_statistic SET `name`="wood step" WHERE `statistic`="woodstep";
UPDATE ${PREFIX}_statistic SET `name`="oak wood step" WHERE `statistic`="woodstep_0";
UPDATE ${PREFIX}_statistic SET `name`="redwood wood step" WHERE `statistic`="woodstep_1";
UPDATE ${PREFIX}_statistic SET `name`="birch wood step" WHERE `statistic`="woodstep_2";
UPDATE ${PREFIX}_statistic SET `name`="jungle wood step" WHERE `statistic`="woodstep_3";
UPDATE ${PREFIX}_statistic SET `name`="wood sword" WHERE `statistic`="woodsword";
UPDATE ${PREFIX}_statistic SET `name`="wool" WHERE `statistic`="wool";
UPDATE ${PREFIX}_statistic SET `name`="white wool" WHERE `statistic`="wool_0";
UPDATE ${PREFIX}_statistic SET `name`="workbench" WHERE `statistic`="workbench";
UPDATE ${PREFIX}_statistic SET `name`="written book" WHERE `statistic`="writtenbook";
UPDATE ${PREFIX}_statistic SET `name`="yellow flower" WHERE `statistic`="yellowflower";
UPDATE ${PREFIX}_statistic SET `name`="zombie" WHERE `statistic`="zombie";

#Done migrating